<?php

/*
 * İnşaat güvenli çalışma talimatları — kullanıcının kendi Word talimatlarından
 * (yeni isg dosya evrakları/Talimatlar/İnşaat Talimatları, 10.10.2026) BİREBİR
 * aktarıldı; metinleri değiştirme. Sıra = "Talimat İçerikleri.xlsx" teslim
 * tutanağındaki sıra. Talimat Oluştur kütüphanesinde hazır şablonların
 * ardından listelenir (App\Support\TalimatKutuphanesi).
 */

return [
    [
        'baslik' => 'ALTYAPI İŞLERİNDE GÜVENLİ ÇALIŞMA TALİMATI',
        'kategori' => 'insaat_saha',
        'dokuman_no' => 'İn_Altyp_tlmt',
        'aciklama' => 'İnşaat talimatı — 30 madde',
        'kkdler' => [],
        'maddeler' => [
            'Kazı alanında kişisel koruyucular (iş ayakkabısı, gözlük, toz maskesi, baret vs) kullanılmalıdır.',
            'Yukarıda çalışma varken aşağısında çalışma yapılmamalıdır. Eğer zorunlu çalışma yapılacaksa yukarıdan malzeme düşmemesi için uygun güvenlik ağları ya da sağlam platformlarla güvenlik önlemi alındıktan sonra çalışma yapılmalıdır. Aksi takdirde çalışma yapılması yasaktır.',
            'Kazı sırasında üst taraftan herhangi bir kayma veya göçme ihtimali belirdiği zaman derhal çalışma mahalli terk edilmelidir. Sorumlu ve ilgililere derhal haber verilmelidir. Gerekli önlemler alındıktan sonra kazı işlemine devam edilmelidir.',
            'Kazı sırasında elektrik kabloları, gaz boruları, su boruları veya suyolu, kanalizasyon ve benzeri tesisata rastlandığı takdirde kazı işlemi derhal durdurulmalı, sorumlu ve ilgililere haber verilmelidir. Sorumlu ve ilgili şahıslar tarafından gerekli önlemler alındıktan sonra kazı işlemine devam edilmelidir.',
            'Kazı derinliği 1,5 metreyi geçen yerlerde şevli ya da iksa mutlaka yapılmalıdır.',
            '1,5m’den daha derin olan kazı işlerinde el merdivenleri ile inip-çıkılmalıdır.',
            'Kazı işlerinde yağış sırasında çalışılmamalıdır. Yağışın durmasından ve güvenlik tedbirleri alındıktan sonra çalışılmalıdır. Batma tehlikesi olan yerlerde çalışılmamalıdır.',
            'Islak elbise ile çalışılmamalıdır.',
            'Su içinde çalışmak gerekiyorsa çizme kullanılmalıdır.',
            'Kazı sahası içinde çalışma dışında bulunulmamalı, oturulmamalı, yatılmamalı ve uyunmamalıdır.',
            'İş makinelerinin hareket alanı içine girilmemeli ve yaklaşılmamalıdır.',
            'İş makineleri üzerine kati surette binilmemelidir. Bu gibi makinelerin üzerinde operatörden başkası bulunmamalıdır.',
            'İş makineleri işaretçisiz kesinlikle çalışmamalıdır.',
            'İş makinelerinizin kabinlerinde kesinlikle dışarıdaki sesi duymayı engelleyecek aletlerin bulunması (teyp, kulaklık, radyo vs) yasaktır.',
            'İş makinelerinizin geri manevralarında mutlaka geri ikaz sesleri ve araç arkalarında işaretçilerin (hop-hopçu) olması zorunludur.',
            'Araçları periyodik kullanacak olan personellerin gerekli ehliyetleri (OPERATÖRLER İÇİN OPERATÖR BELGESİ) olmak zorundadır.',
            'Araçların kontrol bakımlarının bir kopyası şantiye SEÇ Birimine getirilmelidir.',
            'Kazı çalışması sonucunda oluşan boşlukların üzeri kapatılmalı ve etrafı çevrilmelidir. Boşluklara yaklaşılmamalıdır. (altyapı bacaları vs)',
            'Yanıcı ve parlayıcı maddelerin yanında sigara içilmemeli, ateş yakılmamalıdır.',
            'Gece çalışmalarında aydınlatmanın olmadığı yerde çalışma yapılmamalı, şantiye SEÇ Biriminden Gece Çalışma İzni alınmalıdır.',
            'Şantiye sahasında gece çalışmalarında rastgele yerlerde dinlenme yapılmamalıdır.',
            'İskelelere 2m den daha yakın yerlerde kesinlikle kazı yapılmamalıdır.',
            'Kazı çalışması yapıldıktan sonra kazı alanı, hard bariyerler veya alan perdesi ile çevrilmelidir.',
            'Malzeme kaldırma ve taşıma işlemleri uygun araçlarla yapılmalıdır. (Mobil vinç, Hi-Up vinç vs)',
            'Malzeme kaldırma ve taşıma işlemlerinde malzemeler sapan veya zincirlerle bağlanmalıdır. Bağlantı noktaları mapa veya emniyet mandallı kancalarla yapılmalıdır.',
            'Malzeme kaldırma ve taşıma işlemleri sırasında yükün altında bulunulmamalıdır. Kaldırma ve taşıma operasyonlarını eğitimli işaretçiler tarafından yapmalıdır.',
            'Kırım işlemi yapan personel mutlak süretle kulak tıkacı ve gözlük kullanmalıdır.',
            'Komprasör ile kırım yapılıyorsa, komprasörün hortum bağlantıları eksiksiz olarak yapılmalıdır. Orjinal bağlantılarının yerine bağ teli, çivi gibi malzemeler kullanılmamalıdır.',
            'Elektrikli ekipmanların korumaları eksiksiz, kabloları uygun olmalıdır. Uzatma kabloları ekli olmamalı ve topraklamalı olmalıdır. Uygun olmayan ekipman ile çalışma yapılmamalıdır.',
            'Kuyu ve lâğım çukurları gibi derin yerlerde çalışılacaksa ,güvenlik kemeri ve sinyal ipleri gibi uygun koruyucu araçlar kullanılmalıdır.',
        ],
        'bolumler' => NULL,
        'taahhut' => 'Her işçi kendi emniyetini almakla yükümlüdür. Yapılacak işin gereğine uygun olarak iş güvenliği ile ilgili her türlü gereç ve vasıtaları ilgililerden isteyip kullanmak zorundadırlar. Aksi takdirde meydana gelebilecek kaza ve neticelerden ve iş güvenliği talimatlarını bilmemekten dolayı geçireceğiniz veya sebep olacağınız bir kazadan dolayı sorumlu olacağınızı unutmayınız. Yukarıdaki maddeleri tamamen okudum. İş güvenliği ile ilgili eğitimi aldım, işim ve ilgili hususlarda tatbiki gerekenlerin tatbikini yapacağım, eğer yetkim dışında ise derhal yetkilisine ve işyerine müracaat edeceğim. Bu talimat tutanağını tamamen okuyup anlayarak ve iş güvenliği kaidelerine ve talimatlarına harfiyen riayet edeceğimi bildirerek imza ediyorum.',
    ],
    [
        'baslik' => 'FORE KAZIK İŞLERİNDE GÜVENLİ ÇALIŞMA TALİMATI',
        'kategori' => 'insaat_saha',
        'dokuman_no' => 'İn_FRKZK_tlmt',
        'aciklama' => 'İnşaat talimatı — 29 madde',
        'kkdler' => [],
        'maddeler' => [
            'Forekazık makinasını yetkisi ve belgesi olmayan personel kullanmamalıdır.',
            'Gerekli kişisel koruyucu malzemeler (baret, iş ayakkabısı, reflektörlü yelek, iş gözlüğü...vb) kullanılmadan çalışma yapılmamalıdır.',
            'Makina bomuna ve yüksek yerlere emniyet kemeri takılmadan çıkılmamalıdır.',
            'Makina çalışırken operatörün görüş alanında bulunulmalı,makina altında,arkasında, üstünde ve dönüş mesafesinde bulunulmamalıdır.',
            'Demir donatı kaldırma bağlantıları sağlam yapılmalıdır.',
            'Delgisi bitmiş ve betonu dökülmemiş kuyuların üstü kapatılmalıdır.',
            'Derin çukurların etrafı emniyet şeridi ile çevrilmelidir.',
            'Makinanın kaldırdığı demir donatı ve diğer malzemelerin altında durulmamalıdır.',
            'Çalışma esnasında kullanılan muhafaza boruları makinadan ve çalışma sahasından 5-6m uzağa konulmalı ve yere devrilmeyecek şekilde gerekirse 1-2 m ön foraj yapılarak saplanmalıdır.',
            'Operatörün bilgisi ve talimatı haricinde delici ekipman ve aparat sokup takma işlemleri yapılmamalıdır.(Auger,matkap,auger pimi,adaptor pimi)',
            'Kaynak maskesi ve eldiveni olmadan kaynak yapılmamalıdır.',
            'Tozlu alanlarda ,toz maskesi ve gözlük kullanılmadan çalışılmamalıdır.',
            'Kaldırma ekipmanları günlük kontrol edilmeli, zedelenmiş veya hasar görmüş ekipmanlar kullanılmamalıdır.',
            'Makinaların üzerinde malzeme ve alet bulundurulmamalıdır.',
            'Jet motoru ve oksijen takımıyla her türlü metal kesme işlerinde gözlük takılmalıdır.',
            'Delici takımların , makina çenelerinin, muhafaza borularının ve sıkışma olabilecek aralara el sokulmalıdır.',
            'Sahadaki elektrik kabloları zedelenmiş ise kullanılmamalıdır.',
            'Yanıcı maddelerin bulundugu yerde sigara içilmemeli, ateş yakılmamalı, oksijenle ve jet motoruyla kesme işlemi yapılmalıdır.',
            'Makina platformunun uygun olmadığı yerlerde çalışma yapılmamalı ve yüksek kuleli makinalarla yürüyüş yapılmamalıdır.',
            'Makina ile duvar veya sıkışma olabilecek yerlere girilmemelidir.',
            'Kazıkların dikileceği bölge içerisinde elektrik hatları olup olmadığı kontrol edilmelidir.',
            'Hava koşullarına bağlı olarak gerekli önlemler alınmalı, dikme esnasında kılavuz halatlar kullanılmalıdır.',
            'Eğer bir bölgede iki fore kazık dikilecekse bunların birbirlerinden mesafeleri en az uzun olanın yüksekliği kadar olmalıdır.',
            'Buhar ve hidrolik borularının herhangi bir kopma durumunda potansiyel basınç etkisiyle çevresindekilere çarpmasını önlemek amacıyla sıkıca bağlanmalı, günlük kontrolleri yapılmalıdır.',
            'Çakılacak kazık ekipmanlarının istif halinde iken devrilmemesi için önlemler alınmalıdır.',
            'Gece çalışması yapılacaksa kazı çevresinde yeterli aydınlatma koşulları sağlanmalı, foraj deliğinin üzeri kapatılarak, etrafı güvenlik şeridi ile çevrilecek ve ışıklı reflektörler konulmalıdır.',
            'Çalışan makineye el ile veya başka bir malzeme ile müdahale edilmemelidir. Makine çalışırken yağlanmamalı, tamirat veya bakım işlerine girişilmemelidir.',
            'Makine durdurulduktan sonra yapılacak yağlama, tamirat ve bakım sonucunda, makineye ait koruyucuları muhakkak yerine takılmalı. Koruyucuları olmayan makine çalıştırılmamalı veya kullanılmamalıdır. Makinenin çalıştırıldığı kısımdaki uyarı levhasına muhakkak uyulmalıdır..',
            'Rüzgarlı ve şiddetli yağmurlu havalarda çalışma yapılmamalıdır.',
        ],
        'bolumler' => NULL,
        'taahhut' => 'Her işçi kendi emniyetini almakla yükümlüdür. Yapılacak işin gereğine uygun olarak iş güvenliği ile ilgili her türlü gereç ve vasıtaları ilgililerden isteyip kullanmak zorundadırlar. Aksi takdirde meydana gelebilecek kaza ve neticelerden ve iş güvenliği talimatlarını bilmemekten dolayı geçireceğiniz veya sebep olacağınız bir kazadan dolayı sorumlu olacağınızı unutmayınız. Yukarıdaki maddeleri tamamen okudum.
İş güvenliği ile ilgili eğitimi aldım, işim ve ilgili hususlarda tatbiki gerekenlerin tatbikini yapacağım, eğer yetkim dışında ise derhal yetkilisine ve işyerine müracaat edeceğim. Bu talimat tutanağını tamamen okuyup anlayarak ve iş güvenliği kaidelerine ve talimatlarına harfiyen riayet edeceğimi bildirerek imza ediyorum.',
    ],
    [
        'baslik' => 'ENJEKSİYON İŞLERİNDE GÜVENLİ ÇALIŞMA TALİMATI',
        'kategori' => 'insaat_saha',
        'dokuman_no' => 'İn_Enjek_tlmt',
        'aciklama' => 'İnşaat talimatı — 26 madde',
        'kkdler' => [],
        'maddeler' => [
            'Yüksek basınçlı enjeksiyon makinesini ve ekipmanlarını kullanacak işçiler eğitimli olmalıdır.',
            'Gerekli kişisel koruyucu malzemeler (baret, iş ayakkabısı, reflektörlü yelek, iş gözlüğü,toz maskesi vb.) kullanılmadan çalışma yapılmamalıdır.',
            'Çalışma yapılan bölgeye başkalarının girmesini engellemek için uyarı işaret ve levhaları gerekli yerlere koyulmalıdır.',
            'Enjeksiyon seti (karıştırıcı, pompa, manometre sehpası) kontrol edip çalıştırılmalı, pompanın basıp basmadığına bakılmalıdır.',
            'Manometre denenmeli, çalışıp çalışmadığına bakılmalıdır.',
            'Enjeksiyon hortumları denenmeli açık olup olmadıklarına bakılmalıdır.',
            'Enjeksiyon hortum vana ve kurt ağızları kontrol edilmeli, sağlam olmayanları değiştirilmelidir.',
            'Pakerler kontrol edilmeli, deliğe sıkıştırdığında geriye gelmeyecek sağlamlıkta olup olmadığı kontrol edilmelidir.',
            'Enjeksiyon sırasında istenilen basınç sağlanmalı, pompa daha yüksek basınçta amirin talimatı olmadan çalıştırılmamalıdır.',
            'Manometrede basıncın aniden fırlaması halinde pompa devri sıfırlanmalı, enjeksiyon akışı kesilmelidir. Emniyet valfi açılmalıdır.',
            'Eğer basınç yükselmesi meme ucu tıkanmasından kaynaklanıyorsa, öncelikli olarak monitör adaptör bağlantıları açılarak içeride hapis olan basıncın dışarı çıkması sağlanmalıdır. Meme ucu deliklerini açmak için herhangi bir cisim kesinlikle kullanılmamalıdır.',
            'Tıkalı bir meme ucunu açmak için bir araç olarak parmak asla kullanılmamalıdır.',
            'Enjeksiyon memesi kesinlikle vücudun herhangi bir yerine veya etraftaki herhangi bir kişiye tutulmamalıdır.',
            'Hatlar ve manometre kontrol edilmeli, arıza nedeni bulunmalı, arıza giderilmeli ve ondan sonra işe devam edilmelidir.',
            'Enjeksiyon sırasında, tıkanmaları ve arızaları önlemek için kullanılacak çimento, kum gibi malzemeler sık sık kontrol edilmelidir; taşlaşmış malzeme kullanılmamalı, zorunlu olursa elekten geçirerek tıkanmaya neden olacak malzemeler ayıklanmalıdır.',
            'Kumanda panosuna görevli dışında personelin müdahale etmesi yasaktır.',
            'El aletleri amaçları dışında kullanılmamalıdır.',
            'Yüksek basınçlı enjeksiyon ile bir incinme olmuşsa, vücuda enjekte edilen sıvının vücut içerisinde dolaşabilme ihtimaline karşın hemen tıbbi tedavi istenmelidir.',
            'Sistemdeki kaçakların olasılığını azaltmak için sıvı boru sisteminin düzenli güvenlik denetimleri gerçekleştirilmelidir.',
            'Makine gözetimsiz bırakılarak terk edilirken, daima kapatılmalı ve tüm basıncı düşürülmelidir.',
            'Makinenin gerekli bakım ve onarımları zamanında ve düzenli olarak yapılmalıdır.',
            'Gerekli emniyet tedbirleri alınmadan bakım-onarım işleri gerçekleştirilmemelidir.',
            'Çalışma alanına yağ, kimyasal vb. döküldüğünde absorban malzeme (kum, talaş, absorbant vb.) ile emdirilmeli ve emdirilen malzeme tehlikeli atık sahasına yollanmalıdır.',
            'Gece çalışması yapılacaksa yeterli aydınlatma koşulları sağlanmalıdır.',
            'Rüzgarlı ve şiddetli yağmurlu havalarda çalışma yapılmamalıdır.',
            'Enjeksiyon işlemi bittiğinde veya ara verildiğinde tüm ekipman ve hortumlar temizlenmeli, arızalı ve zayıf olanları ayrılmalıdır. Temizlik yapılırken elektrik aksamına su tutulmamalıdır.',
        ],
        'bolumler' => NULL,
        'taahhut' => 'Her işçi kendi emniyetini almakla yükümlüdür. Yapılacak işin gereğine uygun olarak iş güvenliği ile ilgili her türlü gereç ve vasıtaları ilgililerden isteyip kullanmak zorundadırlar. Aksi takdirde meydana gelebilecek kaza ve neticelerden ve iş güvenliği talimatlarını bilmemekten dolayı geçireceğiniz veya sebep olacağınız bir kazadan dolayı sorumlu olacağınızı unutmayınız. Yukarıdaki maddeleri tamamen okudum.
İş güvenliği ile ilgili eğitimi aldım, işim ve ilgili hususlarda tatbiki gerekenlerin tatbikini yapacağım, eğer yetkim dışında ise derhal yetkilisine ve işyerine müracaat edeceğim. Bu talimat tutanağını tamamen okuyup anlayarak ve iş güvenliği kaidelerine ve talimatlarına harfiyen riayet edeceğimi bildirerek imza ediyorum.',
    ],
    [
        'baslik' => 'DEMİR (DONATI) İŞLERİ GÜVENLİ ÇALIŞMA TALİMATI',
        'kategori' => 'insaat_saha',
        'dokuman_no' => 'İn_dmr_tlmt',
        'aciklama' => 'İnşaat talimatı — 16 bölüm (Amaç, Kapsam, KKD, Yasaklar…)',
        'kkdler' => [
            'Baret',
            'Çelik burunlu iş ayakkabısı',
            'Reflektörlü yelek',
            'İş eldiveni',
            'Koruyucu gözlük',
            'Paraşüt tipi emniyet kemeri (≥2 metre yüksekliklerde)',
        ],
        'maddeler' => [],
        'bolumler' => [
            [
                'baslik' => 'AMAÇ',
                'aciklama' => 'Bu talimatın amacı; inşaat sahalarında demir kesme, bükme, taşıma ve montaj işleri sırasında çalışanların sağlık ve güvenliğini sağlamak ve iş kazalarını önlemektir.',
                'maddeler' => [],
            ],
            [
                'baslik' => 'KAPSAM',
                'aciklama' => 'Bu talimat; demir indirme, taşıma, kesme, bükme, stoklama ve montaj işlerinde çalışan tüm personeli kapsar.',
                'maddeler' => [],
            ],
            [
                'baslik' => 'GENEL KURALLAR',
                'aciklama' => '',
                'maddeler' => [
                    'İşe dinlenmiş ve sağlıklı gelinmelidir.',
                    'Uyuşukluk yapan ilaç kullanan çalışanlar amirine bilgi vermelidir.',
                    'Takı (yüzük, kolye vb.), bol ve sarkıntılı kıyafet kullanılmamalıdır.',
                    'İşyerinde şakalaşmak ve dikkati dağıtacak davranışlar yasaktır.',
                    'Tüm çalışanlar iş güvenliği kurallarına uymak zorundadır.',
                    'Tehlikeler derhal amire bildirilmelidir.',
                ],
            ],
            [
                'baslik' => 'KİŞİSEL KORUYUCU DONANIMLAR (KKD)',
                'aciklama' => 'Demir işlerinde aşağıdaki KKD’ler zorunludur:',
                'maddeler' => [
                    'Baret',
                    'Çelik burunlu iş ayakkabısı',
                    'Reflektörlü yelek',
                    'İş eldiveni',
                    'Koruyucu gözlük',
                    'Paraşüt tipi emniyet kemeri (≥2 metre yüksekliklerde)',
                ],
            ],
            [
                'baslik' => 'YÜKLEME, BOŞALTMA VE TAŞIMA',
                'aciklama' => '',
                'maddeler' => [
                    'Kangal demirlerin indirilmesi sırasında yük altında durulmaz ve geçilmez.',
                    'Yükleme/boşaltma işlemleri sadece işaretçi komutuyla yapılır.',
                    'Vinç ile kaldırılan yüklerin altında kimse bulunmaz.',
                    'Malzemeler dengeli bağlanmalı, aşınmış sapanlar kullanılmamalıdır.',
                    'Küçük parçalar malzeme sepeti ile taşınmalıdır.',
                    'Uzun demirler en az iki noktadan bağlanmalıdır.',
                    'Kamyon/TIR üzerinde işçi taşınması yasaktır.',
                ],
            ],
            [
                'baslik' => 'DEMİR MONTAJ VE YÜKSEKTE ÇALIŞMA',
                'aciklama' => '',
                'maddeler' => [
                    'Yüksekte çalışanlar emniyet kemeri kullanmak zorundadır.',
                    'Emniyet kemeri sağlam noktalara bağlanmalıdır.',
                    'Gerekirse can halatı veya güvenlik ağı kurulmalıdır.',
                    'Korkuluksuz alanlarda çalışma yapılmaz.',
                    'İşçiler donatı üzerinde dikkatli yürümelidir.',
                    'Demir uçlarının çarpma ve batma riskine karşı dikkat edilmelidir.',
                ],
            ],
            [
                'baslik' => 'İSKELE VE MERDİVEN KULLANIMI',
                'aciklama' => '',
                'maddeler' => [
                    'İskeleler sağlam, platformlu ve korkuluklu olmalıdır.',
                    'Seyyar merdivenler sağlam ve sabitlenmiş olmalıdır.',
                    'Boşluk kenarlarında merdiven kullanılmaz.',
                    'Tek elle tutunarak çalışma yapılmaz.',
                ],
            ],
            [
                'baslik' => 'DEMİR KESME VE BÜKME İŞLERİ',
                'aciklama' => '',
                'maddeler' => [
                    'Kesme ve bükme makinelerini sadece yetkili kişiler kullanır.',
                    'Makinelerde topraklama yapılmış olmalıdır.',
                    'Arızalı makineler kesinlikle kullanılmaz.',
                    'Makine durmadan bakım ve temizlik yapılmaz.',
                    'Kesme sırasında el ve parmaklar tehlike bölgesinden uzak tutulur.',
                    'Koruyucu kapaklar sökülmez.',
                ],
            ],
            [
                'baslik' => 'ELEKTRİK GÜVENLİĞİ',
                'aciklama' => '',
                'maddeler' => [
                    'Elektrikli aletlerin kabloları hasarsız olmalıdır.',
                    'Kablolar su içinden veya yerde dağınık geçirilmez.',
                    'Uzatma kabloları mümkünse yukarıdan taşınmalıdır.',
                    'Enerji hatlarına yaklaşırken dikkat edilmeli, gerekirse enerji kesilmelidir.',
                ],
            ],
            [
                'baslik' => 'MALZEME DÜZENİ VE İSTİF',
                'aciklama' => '',
                'maddeler' => [
                    'Demirler düzenli istiflenmelidir.',
                    'Kesilen parçalar gelişi güzel atılmamalıdır.',
                    'Bağ telleri ve atıklar belirli alanlarda toplanmalıdır.',
                    'Sivri demir uçları düzeltilmeli veya koruma altına alınmalıdır.',
                    'Çalışma alanı temiz tutulmalıdır.',
                ],
            ],
            [
                'baslik' => 'EL ALETLERİ VE EKİPMAN KULLANIMI',
                'aciklama' => '',
                'maddeler' => [
                    'El aletleri sağlam ve amacına uygun kullanılmalıdır.',
                    'Kullanılmayan aletler uygun yerde muhafaza edilmelidir.',
                    'Kesici ve batıcı aletler cepte taşınmaz.',
                    'Zımpara taşları kontrol edilmeden kullanılmaz.',
                ],
            ],
            [
                'baslik' => 'ÇALIŞMA ORTAMI GÜVENLİĞİ',
                'aciklama' => '',
                'maddeler' => [
                    'Yeterli aydınlatma sağlanmalıdır.',
                    'Kayma ve düşme riskine karşı önlem alınmalıdır.',
                    'Yükseklik farkı olan yerlerde korkuluk yapılmalıdır.',
                    'Enerji hatlarına güvenli mesafe korunmalıdır.',
                ],
            ],
            [
                'baslik' => 'SAĞLIK VE ERGONOMİ',
                'aciklama' => '',
                'maddeler' => [
                    'Ağır yük kaldırırken bel değil dizler kullanılmalıdır.',
                    'Tetanos aşıları yapılmış olmalıdır.',
                    'Uzun süreli zorlanmalara karşı dikkat edilmelidir.',
                ],
            ],
            [
                'baslik' => 'YASAKLAR',
                'aciklama' => '',
                'maddeler' => [
                    'Yük altında durmak yasaktır.',
                    'Malzeme aşağıya atılamaz.',
                    'Hasarlı ekipman kullanılamaz.',
                    'Korkuluksuz alanlarda çalışılamaz.',
                    'Yetkisiz kişiler makine kullanamaz.',
                ],
            ],
            [
                'baslik' => 'ACİL DURUM VE BİLDİRİM',
                'aciklama' => '',
                'maddeler' => [
                    'Tehlikeler derhal amire bildirilmelidir.',
                    'İş kazaları kayıt altına alınmalıdır.',
                    'Acil durum prosedürlerine uyulmalıdır.',
                ],
            ],
            [
                'baslik' => 'ÇALIŞAN YÜKÜMLÜLÜKLERİ',
                'aciklama' => '',
                'maddeler' => [
                    'KKD kullanımı zorunludur.',
                    'İş güvenliği kurallarına uyulmalıdır.',
                    'Güvenlik ekipmanları izinsiz kaldırılmamalıdır.',
                    'Güvensiz durumlarda çalışma durdurulmalıdır.',
                ],
            ],
        ],
        'taahhut' => 'Bu talimatı okudum, anladım ve iş sağlığı ve güvenliği kurallarına uygun çalışacağımı kabul ederim.',
    ],
    [
        'baslik' => 'KALIP İŞLERİ GÜVENLİ ÇALIŞMA TALİMATI',
        'kategori' => 'insaat_saha',
        'dokuman_no' => 'İn_klp_tlmt',
        'aciklama' => 'İnşaat talimatı — 16 bölüm (Amaç, Kapsam, KKD, Yasaklar…)',
        'kkdler' => [
            'Baret',
            'Çelik burunlu ve tabanlı iş ayakkabısı',
            'İş eldiveni',
            'Koruyucu gözlük',
            'Reflektörlü yelek',
            'Paraşüt tipi emniyet kemeri (yüksekte çalışma)',
            'Gerekli durumlarda maske ve kulaklık',
        ],
        'maddeler' => [],
        'bolumler' => [
            [
                'baslik' => 'AMAÇ',
                'aciklama' => 'Bu talimatın amacı; şantiyelerde gerçekleştirilen betonarme kalıp işleri sırasında çalışanların sağlık ve güvenliğini sağlamak, iş kazalarını ve meslek hastalıklarını önlemektir.',
                'maddeler' => [],
            ],
            [
                'baslik' => 'KAPSAM',
                'aciklama' => 'Bu talimat; kalıp kurma, sökme, taşıma, beton dökümü ve kalıp ile ilgili tüm faaliyetlerde çalışan personeli kapsar.',
                'maddeler' => [],
            ],
            [
                'baslik' => 'GENEL KURALLAR',
                'aciklama' => '',
                'maddeler' => [
                    'İşe dinlenmiş ve sağlıklı şekilde gelinmelidir.',
                    'Uyuşukluk yapan ilaç kullanan çalışanlar durumu amirine bildirmelidir.',
                    'Takı (yüzük, kolye vb.), bol kıyafet ve sarkıntılı elbise kullanılmamalıdır.',
                    'Tüm çalışanlar verilen Kişisel Koruyucu Donanımları (KKD) kullanmak zorundadır.',
                    'İş alanında temizlik ve düzen sağlanmalıdır.',
                    'Tehlikeli durumlar derhal amir veya iş güvenliği uzmanına bildirilmelidir.',
                ],
            ],
            [
                'baslik' => 'KİŞİSEL KORUYUCU DONANIMLAR (KKD)',
                'aciklama' => 'Kalıp işlerinde çalışanlar aşağıdaki ekipmanları kullanmak zorundadır:',
                'maddeler' => [
                    'Baret',
                    'Çelik burunlu ve tabanlı iş ayakkabısı',
                    'İş eldiveni',
                    'Koruyucu gözlük',
                    'Reflektörlü yelek',
                    'Paraşüt tipi emniyet kemeri (yüksekte çalışma)',
                    'Gerekli durumlarda maske ve kulaklık',
                ],
            ],
            [
                'baslik' => 'KALIP KURULUMU GÜVENLİK KURALLARI',
                'aciklama' => '',
                'maddeler' => [
                    'Kalıp dikmeleri yeterli sağlamlıkta ve taşıyacağı yüke uygun olmalıdır.',
                    'Hasarlı malzemeler kesinlikle kullanılmamalıdır.',
                    'Kalıp elemanları birbirine sağlam ve sıkı şekilde bağlanmalıdır.',
                    'Kiriş tabanları yeterince desteklenmeden üzerine çıkılmamalıdır.',
                    'Kalıp kenarlarına korkuluk ve güvenlik ağı yapılmalıdır.',
                    'Kalıp boşlukları (şaft, asansör, merdiven vb.) kapatılmalıdır.',
                    'Servis yolları sağlam, temiz ve korkuluklu olmalıdır.',
                    'Dikmeler kaymaya karşı sabitlenmeli ve çapraz bağlantılar yapılmalıdır.',
                ],
            ],
            [
                'baslik' => 'YÜKSEKTE ÇALIŞMA KURALLARI',
                'aciklama' => '',
                'maddeler' => [
                    '2 metre ve üzeri çalışmalarda emniyet kemeri kullanımı zorunludur.',
                    'Emniyet kemeri uygun ve sağlam noktalara bağlanmalıdır.',
                    'Korkuluksuz alanlarda çalışma yapılmamalıdır.',
                    'El aletleri düşmeye karşı emniyetli şekilde muhafaza edilmelidir.',
                    'Gerekli durumlarda iskele, platform veya güvenlik ağı kullanılmalıdır.',
                ],
            ],
            [
                'baslik' => 'MERDİVEN VE İSKELE KULLANIMI',
                'aciklama' => '',
                'maddeler' => [
                    'Seyyar merdivenler sağlam, eksiksiz ve kaymaz olmalıdır.',
                    'Basamak aralıkları en fazla 30 cm olmalıdır.',
                    'Merdivenler üst ve alt noktadan sabitlenmelidir.',
                    'Boşluk kenarlarında merdiven yerine korkuluklu iskele kullanılmalıdır.',
                    'İskeleler korkuluklu ve güvenli olmalıdır.',
                ],
            ],
            [
                'baslik' => 'KALIP SÖKÜM KURALLARI',
                'aciklama' => '',
                'maddeler' => [
                    'Söküm işlemi kontrollü ve aşamalı yapılmalıdır.',
                    'Aynı anda en fazla iki aks sökülmelidir.',
                    'Dikmelere tırmanılmamalı, iskele kullanılmalıdır.',
                    'Sökülen malzemeler aşağıya atılmamalıdır.',
                    'Söküm alanına yetkisiz kişiler girmemelidir.',
                    'Malzemeler düzenli şekilde istiflenmelidir.',
                ],
            ],
            [
                'baslik' => 'MALZEME TAŞIMA VE VİNÇ KULLANIMI',
                'aciklama' => '',
                'maddeler' => [
                    'Vinç ile taşıma sırasında kimse yük altında bulunmamalıdır.',
                    'Yükler dengeli bağlanmalı, uygun sapan kullanılmalıdır.',
                    'Hasarlı halat, kanca ve zincir kullanılmamalıdır.',
                    'İşaretçi ile operatör arasında iletişim sağlanmalıdır.',
                    'Rüzgarlı havalarda (45 km/s üzeri) çalışma durdurulmalıdır.',
                ],
            ],
            [
                'baslik' => 'EL ALETLERİ VE EKİPMAN KULLANIMI',
                'aciklama' => '',
                'maddeler' => [
                    'Tüm el aletleri amacına uygun ve sağlam olmalıdır.',
                    'Elektrikli aletlerin bağlantıları yetkili kişiler tarafından yapılmalıdır.',
                    'Hasarlı kablo ve ekipman kullanılmamalıdır.',
                    'Kullanılmayan aletler fişten çekilmelidir.',
                    'Kesici aletler güvenli şekilde muhafaza edilmelidir.',
                ],
            ],
            [
                'baslik' => 'BETON DÖKÜMÜ GÜVENLİĞİ',
                'aciklama' => '',
                'maddeler' => [
                    'Beton dökümü sırasında KKD kullanımı zorunludur.',
                    'Vibratörler çalıştırılmadan önce kontrol edilmelidir.',
                    'Beton kovaları ve ekipmanları kontrol edilmelidir.',
                    'Pompa hortumlarına asılınmamalıdır.',
                    'Düşme riski olan alanlarda emniyet önlemleri alınmalıdır.',
                ],
            ],
            [
                'baslik' => 'ELEKTRİK VE YANGIN GÜVENLİĞİ',
                'aciklama' => '',
                'maddeler' => [
                    'Elektrik ekipmanları düzenli kontrol edilmelidir.',
                    'Kablolar zarar görmeyecek şekilde yerleştirilmelidir.',
                    'Açık alev kalıp malzemelerine yaklaştırılmamalıdır.',
                    'Sigara izmaritleri söndürülmeden atılmamalıdır.',
                    'Yangın söndürme ekipmanları hazır bulundurulmalıdır.',
                ],
            ],
            [
                'baslik' => 'ÇALIŞMA ORTAMI GÜVENLİĞİ',
                'aciklama' => '',
                'maddeler' => [
                    'Çalışma alanı yeterince aydınlatılmış olmalıdır.',
                    'Kayma riskine karşı önlem alınmalıdır.',
                    'Gece çalışmalarında dikkatli olunmalıdır.',
                    'Kazı alanlarında göçük riskine karşı önlem alınmalıdır.',
                    'Enerji hatlarına yaklaşım mesafesine dikkat edilmelidir.',
                ],
            ],
            [
                'baslik' => 'YASAKLAR',
                'aciklama' => '',
                'maddeler' => [
                    'Kalıp elemanlarına tırmanmak yasaktır.',
                    'Malzeme aşağıya atılamaz.',
                    'Hasarlı ekipman kullanılamaz.',
                    'Korkuluksuz alanlarda çalışma yapılamaz.',
                    'Yetkisiz kişiler iş güvenliği ekipmanlarını sökemez.',
                ],
            ],
            [
                'baslik' => 'ACİL DURUM VE BİLDİRİM',
                'aciklama' => '',
                'maddeler' => [
                    'Tehlike durumları derhal yetkililere bildirilmelidir.',
                    'İş kazaları anında rapor edilmelidir.',
                    'Acil durum prosedürlerine uyulmalıdır.',
                ],
            ],
            [
                'baslik' => 'ÇALIŞAN YÜKÜMLÜLÜKLERİ',
                'aciklama' => '',
                'maddeler' => [
                    'Tüm iş güvenliği kurallarına uymak zorunludur.',
                    'KKD kullanımı ihmal edilmemelidir.',
                    'İş güvenliği ekipmanları izinsiz kaldırılmamalıdır.',
                    'Güvenli olmayan durumlarda çalışma durdurulmalıdır.',
                ],
            ],
        ],
        'taahhut' => 'Bu talimatı okudum, anladım ve iş sağlığı ve güvenliği kurallarına uygun şekilde çalışacağımı kabul ederim.',
    ],
    [
        'baslik' => 'İZALASYON İŞLERİNDE GÜVENLİ ÇALIŞMA TALİMATI',
        'kategori' => 'insaat_saha',
        'dokuman_no' => 'İn_İZYN_tlmt',
        'aciklama' => 'İnşaat talimatı — 12 madde',
        'kkdler' => [],
        'maddeler' => [
            'Bütün personelce şantiye sahasında kesinlikle işin gerektirdiği kişisel koruyucular (baret, iş ayakkabısı, emniyet kemeri, maske, ısıya ve ateşe dayanıklı donanımlar) kullanılmalıdır.',
            'Yüksek yerlerde ve düşme tehlikesi olan yerlerde mutlaka emniyet kemerleri kullanılmalıdır.',
            'İş için kullanılan lpg tüplerin; bağlantı kelepçeleri uygun olmalı, alev geri tepme aparatları olmalı, tüplerin yerleri ateşlerden ve üzerine malzeme düşmesini tüpün aşağıya düşmesini engelleyecek yerlerde muhafaza edilmeli, ventillerinin kapalılığına dikkat edilmeli boş tüplerde kapatılmalı, taşıma yöntemleri dik durmalıdır. İşe başlamadan lpg kontrolleri yapılmalıdır.',
            'Her tüpün yanlarında yangın tüpleri bulundurulmalıdır.',
            'Yangın esnasında; yangın var diye sesli uyarı yapılmalı yangın tüpü yangının kaynağına tutacak şekilde kullanılmalıdır.',
            'Eğer tüpte kaçak olursa; mutlaka hemen yetkililere haber verilmeli, herkesin ortamdan çıkması sağlanmalı, elektrikler kesilmeli, kıvılcıma neden olan unsurlardan uzak durulmalıdır.',
            'Kimyasal koku ve dumanlara karşı mutlaka maske kullanılmalıdır.',
            'Kazı kenarlarındaki çalışmalarda mutlaka bir yetkilinin gözetiminde ve izin alınarak işe başlanmalıdır.',
            'Kazı derinliği 1,5 metreyi geçen yerlerde şevli ya da iksa mutlaka yapılmalıdır.',
            'Yağışlı havalarda kazı kenarlarında azami dikkatle çalışılmalıdır.',
            '18 yaşından küçük ve SSK, iş güvenliği ve revir kayıtları olmadan çalışma yapmak yasaktır.',
            'Yukarıda çalışma varken aşağısında çalışma yapılmamalıdır. Eğer zorunlu çalışma yapılacaksa yukarıdan malzeme düşmemesi için uygun güvenlik ağları ya da sağlam platformlarla güvenlik önlemi alındıktan sonra çalışma yapılmalıdır. Aksi takdirde çalışma yapılması yasaktır.',
        ],
        'bolumler' => NULL,
        'taahhut' => 'Her işçi kendi emniyetini almakla yükümlüdür. Yapılacak işin gereğine uygun olarak iş güvenliği ile ilgili her türlü gereç ve vasıtaları ilgililerden isteyip kullanmak zorundadırlar. Aksi takdirde meydana gelebilecek kaza ve neticelerden ve iş güvenliği talimatlarını bilmemekten dolayı geçireceğiniz veya sebep olacağınız bir kazadan dolayı sorumlu olacağınızı unutmayınız. Yukarıdaki maddeleri tamamen okudum.
İş güvenliği ile ilgili eğitimi aldım, işim ve ilgili hususlarda tatbiki gerekenlerin tatbikini yapacağım, eğer yetkim dışında ise derhal yetkilisine ve işyerine müracaat edeceğim. Bu talimat tutanağını tamamen okuyup anlayarak ve iş güvenliği kaidelerine ve talimatlarına harfiyen riayet edeceğimi bildirerek imza ediyorum.',
    ],
    [
        'baslik' => 'DUVAR İŞLERİNDE GÜVENLİ ÇALIŞMA TALİMATI',
        'kategori' => 'insaat_saha',
        'dokuman_no' => 'İn_Duvar_tlmt',
        'aciklama' => 'İnşaat talimatı — 21 madde',
        'kkdler' => [],
        'maddeler' => [
            'İş Güvenliği ile ilgili verilen; baret, çelik burunlu ayakkabı/bot/çizme, baş ve yüz maskesi, koruyucu gözlük, emniyet kemeri, eldiven gibi koruyucu malzemeler işin gereğine göre mutlaka kullanılmalıdır.',
            'Cephe ve düşme tehlikesi olan boşluklarda yapılan çalışmalar esnasında, 2 metreden yüksek yerlerde paraşüt tipi emniyet kemeri ve can halatı kullanılmalıdır.',
            'Çalışma alanı boyunca yatay hayat halatı gerilerek emniyet kemeri bu halatlara takılıp çalışılmalıdır.',
            'Harçlı çalışmalarda toz maskesi,koruyucu gözlük, eldiven kullanılmalıdır.',
            'Uygun sıpa iskele, merdiven sehpa kullanılmalıdır.',
            'Sıpa iskelelerde ayakların sağlam, eksiz olması, uygun genişlikte ve en az 2 kalastan oluşmuş platform yapılması sağlanmalıdır.',
            'Çelik borulu iskeleler sağa ve sola sallanmayacak şekilde, yeteri kadar çapraz borularla takviye edilmeli ve binadan ayrılmayacak şekilde tespit olunmalıdır.',
            '1 m den yüksek yerlere erişmek için ahşap merdiven kullanılmamalı, standartlı, demir yada aliminyum merdiven kullanılmalıdır.',
            'Merdivenler yaklaşık 75 derecelik bir açı yapacak şekilde veya her 4 birim yükseklik için zeminde 1 birim açıklık bırakarak yerleştirilecek, ayaklar kaygan olmayan hareketsiz ve sağlam bir zemin üzerine sabitlenmelidir.',
            'Blok içerisinde ve dış cephelerde; düşme tehlikesi olan yerlerdeki her türlü güvenlik tedbirlerinin (korkuluklar, kapamalar ) imalat nedeniyle yerinden alınması gerekiyorsa SEÇ Biriminden izin alınarak kaldırılmalıdır.',
            'Malzeme düşmesine karşı gerekli tedbirler alınacak, malzeme istifleri yapı kenarlarında yapılmamalıdır.',
            'Döşemelerde hiçbir şekilde boşluk ve aralıklar bırakılmamalıdır.',
            'Asansör kuyuları yada şaftlara girilmemelidir.',
            'Yatay-dikey malzeme taşımaları uygun ekipmanlar ile yapılmalı, malzeme ve insan düşmesine karşı gerekli tedbirler alınmadan çalışma yapılmamalıdır.',
            'Kullanılan taşıma ekipmanı için hazırlanmış talimata (caraskal,mobil vinç,gırgır vinç...vb) uyulmalıdır.',
            'Katlardan malzeme atımı yapılmayacak, çuvallanarak kontrollü bir şekilde aşağıya indirilmelidir.',
            'Kesici el aletlerini kullanırken korumalı kullanılmalıdır.',
            'Fiş-priz tertibatı olmayan hiçbir elektrikli ekipman,uzatma kablosu sahada kullanılmamalıdır.',
            'Elektrikli el aletleri ıslak yerlerde muhafaza edilmeyecek standartlara uygun elektrik malzemeleri kullanılmalıdır.',
            'Yeterli aydınlatma yapılmadan gece çalışması yapılmamalıdır.',
            'Yanıcı, parlayıcı, çözücü ve incelticiler ısı ve ateşten uzakta tutulmalıdır.',
        ],
        'bolumler' => NULL,
        'taahhut' => 'Her işçi kendi emniyetini almakla yükümlüdür. Yapılacak işin gereğine uygun olarak iş güvenliği ile ilgili her türlü gereç ve vasıtaları ilgililerden isteyip kullanmak zorundadırlar. Aksi takdirde meydana gelebilecek kaza ve neticelerden ve iş güvenliği talimatlarını bilmemekten dolayı geçireceğiniz veya sebep olacağınız bir kazadan dolayı sorumlu olacağınızı unutmayınız. Yukarıdaki maddeleri tamamen okudum.
İş güvenliği ile ilgili eğitimi aldım, işim ve ilgili hususlarda tatbiki gerekenlerin tatbikini yapacağım, eğer yetkim dışında ise derhal yetkilisine ve işyerine müracaat edeceğim. Bu talimat tutanağını tamamen okuyup anlayarak ve iş güvenliği kaidelerine ve talimatlarına harfiyen riayet edeceğimi bildirerek imza ediyorum.',
    ],
    [
        'baslik' => 'İSKELE KURULUM SÖKÜM İŞLERİNDE GÜVENLİ ÇALIŞMA TALİMATI',
        'kategori' => 'insaat_saha',
        'dokuman_no' => 'İn_İKS_tlmt',
        'aciklama' => 'İnşaat talimatı — 42 madde',
        'kkdler' => [],
        'maddeler' => [
            'Yapı iskeleleri, ancak sorumlu ve yetkili teknik elemanın yönetimi altında, tecrübeli ustalara iskele ölçüleri ve malzeme özellikleri göz önünde bulundurularak kurdurulmalı veya söktürülmelidir.',
            'İskele kurulum ve söküm işlerinde çalışacak kişiler sağlık ve psikolojik açıdan uygun olmalıdır.',
            'İskelenin kurulacağı alanın kurulumdan önce zeminin uygunluğunu bağlı bulunduğu firmanın iş güvenliği sorumlusuyla birlikte kontrol edilmeli. Zeminde oturmalara ve çökmeye karşı zeminin sıkıştırılmasını sağlayın. Zemin sağlam değilse uygun metodla zemin kuvvetlendirilmelidir.',
            'İskele montajında, sökümünde ve diğer tehlike arzeden iskele üzerindeki faaliyetlerde, tehlikeli bölgeler şeritlerle çevrilmeli,gerekirse bu bölgelere gözcü yerleştirilmelidir.',
            'İskele çalışma bölgesi yer kısmında “Dikkat Yüksekte Çalışma Var!”, “Çalışma Bölgesi, Girmek Tehlikeli ve Yasaktır!” , “Dikkat! Parça düşebilir!” vb. uyarı-ikaz levhaları konulmalıdır.',
            'İskele üzerinde çalışmalarda gayri ciddi çalışmak (şakalaşmak vb.) yasaktır.',
            'İskelelerin dışından tırmanmak,uygun olmayan yerlerden iskeleye ulaşım tehlikeli ve yasaktır.İskelelerin orjinal merdivenleri kullanılmalıdır.',
            'İskele montajında, sökümünde ve diğer tehlike arzeden iskele üzerindeki faaliyetlerde, çalışanlar paraşüt tip emniyet kemeri kullanmalıdır.',
            'Yapılan iskele kurulum-söküm işlerinde her işçi için ayrı birer can halatı (min. 14 lük polyester örgü) yukarıda sağlam yerlere takılarak aşağıya sarkıtılmalı ve altlarına uygun bir ağırlık takılmalıdır.',
            'İşçiler bellerindeki emniyet kancalarını bu can halatları üzerinde bulunan emniyet kilitlerine veya halat kavrama teçhizatlarına, eğer bunlar yok ise halat üzerindeki belli aralıklarla yapılan gözlerine takacaklardır.',
            'Emniyet kemerleri ve eklentileri,can halatları ,emniyet kilitleri ve halat aparatları her çalışmadan önce iyice kontrol edilmeli, en ufak bir arıza ve bozukluk halinde kullanılmamalı ve yenileri ile değiştirilmelidir.',
            'Taban kalasları plana göre yerleştirilmelidir.',
            'İskelelerin kurulacak olduğu malzemeler (çaprazlar,platformlar vs.) hasarlı olmamalıdır,orjinal malzemeler kullanılmalıdır.',
            'Ayar milleri (taban plakası) yerleştirilmeli, mobil iskele kuruluyorsa uygun tekerlek ve kilit sistemi yerleştirilmelidir.',
            'Ayar milinin üzerine başlangıç ayağı yerleştirilmelidir.',
            'İlk yatay bağlantıları atarak iskele modülü teraziye alınmalıdır.',
            'Dikey, yatay ve çapraz elemanları montaj planına göre yerleştirilmelidir.',
            'Planına uygun merdiven ve yürüme platformları kurulmalıdır.Kurulan platformların aralarında boşluk kalmayacak şekilde montajı yapılmalıdır.Platformlar düzgün kurulmalıdır.',
            'Sistem tekrar teraziye alınmalıdır.',
            'İskelenin kaçak elektriğe karşı topraklanması sağlanmalı,topraklama yapılan yere topraklama levhası asılmalıdır.',
            'Gerekli güvenlik tedbirleri ve yüksekten düşmeyi önleyici güvenlik tedbirleri alınarak bir üst kata çıkılmalıdır.',
            'Üst, orta ve yan korkuluklar yerleştirilmelidir.',
            'Süpürgelikler (topukluklar) yerleştirilmelidir.',
            'İskeleyi sabit bir yüzeye bağlarken planına ve standartlara uygun şekilde ankrajlama (tijler) yapılmalıdır.',
            'İskele elemanlarının bir üst kata taşınması için gerekliyse uygun kaldırma araçlarının kurulumu yapılmalıdır.',
            'Hazırlanan kontrol formuna göre şantiye yetkilisi ile birlikte iskelenin kontrolü yapılmalı ve varsa eksiklikleri giderilmelidir.',
            'Her vardiya başında iskelenin çalışma koşullarına uygunluğunu kontrol edilmelidir.',
            '40 km-saat’in üzerinde rüzgâr hızlarında, zeminin kaygan ve buzlu olması halinde yüksekte yapılan her türlü montaj, bakım ve onarım çalışmaları durdurulmalıdır.',
            'İskelelerin yağmur, kar, buz veya benzeri nedenlerle kayganlaşması halinde, kaymayı önleyecek tedbirler alınmalıdır.',
            'İskeleler her fırtınadan sonra kontrol edilmelidir.',
            'İskelelerde görülecek arızalar derhal onarılmalı, zayıf kısımlar kuvvetlendirilmeli veya yenileri ile değiştirilmelidir.',
            'Çalışma yapılacak iskeleler günlük olarak göz ile kontrol edilmeli,bağlantı elemanları (kelepçe vs.),yatay,düşey korkuluklar vb. kısımlar sağlam ve eksiksiz olmalıdır. Gerekli iskele etiketleri kullanılmalıdır. Uygun olan iskeleler için yeşil, uygun olmayan iskeleler için kırmızı etiketler kullanılmalıdır.Kontrollerden sonra etiketlerde tekrar gerekli güncelleme yapılmalıdır.',
            'İskele kurulum-söküm işlerinde gece çalışmalarında yeterli aydınlatma sağlanmalıdır.',
            'Vinç veya benzeri makinaların kullanılmasında, yüklenen malzemenin iskeleye takılarak iskelenin yıkılmasını veya herhangi bir kaza veya zarar oluşmasını önleyecek tedbirler alınmalıdır.',
            'İskeleler üzerine ağır malzemeleri,moloz ve artıklar ile geçişi engelleyecek malzeme bırakılmamalıdır.',
            'Söküme başlamadan önce kurulum- söküm kılavuzuna uygun olarak şantiye tarafından gerekli önlemlerin alınması sağlanmalıdır.',
            'Söküme başlamadan önce herhangi bir sebeple, iskelenin takviye veya çaprazlarından hiçbir eleman alınmamalıdır. Ancak söküme başlandıktan sonra iskele malzemesinin indirilmesi amacıyla iki dikme arası (aks) korkuluklarının alınması mümkündür.',
            'İskelelerin sökülmesine en üst kısımdan başlanmalıdır.',
            'İskelelerin bina bağlantıları kalasların alınmasından sonra ve yukarıdan aşağıya sırayla sökülmelidir.',
            'Sökülmüş olan malzeme hangi yükseklikten olursa olsun doğrudan doğruya yere atılmamalı, iki yerinden bağlanarak dengeli şekilde indirilmeli ve uygun bir yere istif edilmelidir.',
            'İskele montaj-demontaj çalışanı ,iskele elemanlarını türlerine ve boyutlarına göre ayırmalıdır.Çalışma alanı düzenli tertipli tutulmalıdır.',
            'Temizlik için işçilerin sorumluluğuna verilen malzemeler korunmalı, bakımları yapılmalı ve depolanmalıdır.',
        ],
        'bolumler' => NULL,
        'taahhut' => 'Her işçi kendi emniyetini almakla yükümlüdür. Yapılacak işin gereğine uygun olarak iş güvenliği ile ilgili her türlü gereç ve vasıtaları ilgililerden isteyip kullanmak zorundadırlar. Aksi takdirde meydana gelebilecek kaza ve neticelerden ve iş güvenliği talimatlarını bilmemekten dolayı geçireceğiniz veya sebep olacağınız bir kazadan dolayı sorumlu olacağınızı unutmayınız. Yukarıdaki maddeleri tamamen okudum.
İş güvenliği ile ilgili eğitimi aldım, işim ve ilgili hususlarda tatbiki gerekenlerin tatbikini yapacağım, eğer yetkim dışında ise derhal yetkilisine ve işyerine müracaat edeceğim. Bu talimat tutanağını tamamen okuyup anlayarak ve iş güvenliği kaidelerine ve talimatlarına harfiyen riayet edeceğimi bildirerek imza ediyorum.',
    ],
    [
        'baslik' => 'YÜKSEKTE YAPILAN İŞLERİNDE GÜVENLİ ÇALIŞMA TALİMATI',
        'kategori' => 'insaat_saha',
        'dokuman_no' => 'İn_YYİ_tlmt',
        'aciklama' => 'İnşaat talimatı — 30 madde',
        'kkdler' => [],
        'maddeler' => [
            'Yüksekliği tabandan itibaren 2 metreden daha fazla olan ve düşme veya kayma tehlikesi bulunan yerlerde çalışanlarla, kiremit döşeyicilerine, oluk ve her türlü dış boya işleri yapanlara, gırgır vinçlerini çalıştıranlara ve kuyu, lağım, galeri ve benzeri derinliklerde çalışanlara emniyet kemerleri verilecek ve işçiler de verilen bu kemerleri kullanacaklardır.',
            'Yüksek betonarme platformlarının döşeme kenarlarına düşmeyi önleyecek korkuluk yapılacaktır. Bu mümkün olmadığı hallerde, serbest çalışmayı sağlamak için döşeme kenarına korkuluklu iskele yapılacaktır.',
            'Döşeme kenarları en azından, uyarı niteliğinde kırmızı-beyaz renkli şerit bant ile sarılmalıdır.',
            'Yük taşıyan iskelelerde alet ve malzemenin düşerek kazaya sebep olmasını önlemek için döşeme dış kısmına 15 santimetre yüksekliğinde bir etek tahtası konacaktır.',
            'İskele üzerinde yapılan çalışma anında, iskelelerde köprü görevi görecek geçitler, 60 santimetreden dar ve korkuluksuz yapılmayacaktır.',
            'Çelik borulu iskeleler, sağa ve sola sallanmayacak şekilde yeteri kadar çapraz borularla takviye edilecek ve binadan ayrılmayacak şekilde tespit olunacaktır.',
            'Çelik borulu iskelelerdeki platformlarda kullanılacak kalas veya diğer ahşap kısımların özellikleri ile kullanılacak çaprazlar, korkuluklar, ara korkuluklar ve benzeri kısımlardaki aralıklar aranan özelliklere uygun ve sağlam yapıda olacaktır.',
            'Boru veya madeni iskeleler statik, elektriğe karşı uygun şekilde topraklanacaktır.Bu koşullar sağlanmadan iskele üzerine kesinlikle çıkılmayacaktır.',
            'Alçak veya yüksek seviyede olan hareketli veya sabit çalışma yerleri;
a. çalışan işçi sayısı,
b. üzerlerinde bulunabilecek maksimum ağırlık ve bu ağırlığın dağılımı,
c. maruz kalabileceği dış etkiler,
göz önüne alınarak yeterli sağlamlık ve dayanıklılıkta olacaktır. Bu çalışma yerlerinin taşıyıcı sistemleri ve diğer kısımları yapısı gereği yeterli sağlamlıkta değilse, çalışma yerinin tamamının veya bir kısmının zamansız veya kendiliğinden hareketini önlemek için, bunların dayanıklılığı uygun ve güvenilir sabitleme metotlarıyla sağlanacaktır.',
            'Çalışma yerlerinin sağlamlığı ve dayanıklılığı uygun şekilde ve özellikle de çalışma yerinin yükseklik veya derinliğinde değişiklik olduğunda kontrol edilecektir.',
            'Yüksekten düşmeler, özellikle yeterli yükseklikte sağlam korkuluklarla veya aynı korumayı sağlayabilen başka yollarla önlenecektir. Korkuluklarda en az; bir trabzan, orta seviyesinde bir ara korkuluk ve tabanında eteklik bulunacaktır.',
            'Yüksekte çalışmalar ancak uygun ekipmanlarla veya korkuluklar, platformlar, güvenlik ağları gibi toplu koruma araçları kullanılarak yapılacaktır. İşin doğası gereği toplu koruma önlemlerinin uygulanmasının mümkün olmadığı hallerde, çalışma yerine ulaşılması için uygun araçlar sağlanacak,(sepetli iş makinaları,yükseklikli çalışma platformları vb.) çalışılan yerde vücut tipi emniyet kemeri veya benzeri güvenlik yöntemleri kullanılacaktır.',
            'Çalışma platformları, geçitler ve iskele platformları, kişileri düşmekten ve düşen cisimlerden koruyacak şekilde yapılacak, boyutlandırılacak, kullanılacak ve muhafaza edilecektir.',
            'Merdivenler yeterli sağlamlıkta olacak ve uygun şekilde bakım ve muhafazası sağlanacaktır. Bunlar uygun yerlerde ve amaçlarına uygun olarak doğru bir şekilde kullanılacaktır.',
            'Seyyar iskelelerin kendiliğinden hareket etmemesi için gerekli önlem alınacaktır.',
            'Bütün kaldırma araçları ile(insan taşıyan sepetli iş makinaları,yükseklikli çalışma platformları vb.) bağlantıları, sabitleme ve destekleme elemanları da dahil bütün yardımcı kısımları;Kullanım amacına uygun ve yeterli sağlamlıkta tasarlanmış ve imal edilmiş olacak,Doğru şekilde kurulacak ve kullanılacak,Her zaman iyi çalışabilir durumda olacak,Yürürlükteki mevzuata göre, periyodik olarak kontrol, test ve deneyleri yapılacak,Bu konuda eğitim almış ehil kişilerce kullanılacaktır.',
            'Kaldırma ekipmanı ve aksesuarları belirlenen amacı dışında kullanılmayacaktır.',
            'İşçilerin çatı üzerinde veya kenarında veya kırılgan malzemeden yapılmış herhangi bir yüzey üzerinde çalışmak zorunda olduğu hallerde; kırılgan maddeden yapılmış yüzeyde dalgınlıkla yürümelerini veya yere düşmelerini önleyecek önlemler alınacaktır.',
            'Çatı eğimlerinin 45 dereceyi aştığı durumlarda, çatı, kaymayı önleyici çatı el merdiveni ya da iskele platformu gibi bir destek sistemi olmaksızın çalışmaya uygun değildir. Gerekli tedbirler alınmadan kesinlikle çatı üzerine çıkılmayacaktır.',
            'İskele çalışanlarının emniyetli çalışma sistemleri olmalıdır, böyle bir sistem yoksa iskele çalışanları koşumlar(paraşüt ipli emniyet kemeri vb.) ve çıma halatları içeren koruma cihazları kullanmalıdır.',
            'İskele üzerinde yalnız başlarına çalışmamalıdır. Tüm vücut koşumu içinde asılı kalmış olan işçiler mümkün olduğunca çabuk kurtarılmalıdır. Bundan dolayı, işçiler, düşmüş bir işçinin kurtarılması harekatını gerçekleştirebilecek kapasitede ve saha içi kurtarma ekipmanı ve prosedürlerine de aşina olmalıdır.',
            'Yükseltmeli çalışma platformu – ters dönme ihtimaline karşı ya da bir kaçış cihazı yoluyla tahliye edilmesi gerektiği durumlarda yükseltmeli çalışma platformunda bir tüm vücut koşumu(çalışan işçiyi ikinci bir emniyet halatıyla bağlayan güvenlik ekipmanı) ve düşüş kesme ekipmanı(işçi platformdan düştüğü zaman işçinin yere çarpmasını engelleyen ekipman)i emniyet koşumu kullanan işçiler gerekli değildir.',
            'Hafif-çalışma asma platform (sallanır platform) – her bir vinçte bir tel halatla asılı tutulan sallanır platformda çalışmakta olan herkes, ankraja bağlanmış bağımsız bir emniyet halatına bağlı birer emniyet koşumu ve çıma halatı giymelidir.',
            'El merdivenin düzgün ve yatay bir alana, alt kısmı ile duvar arasındaki mesafe dikey boyunun yaklaşık ¼’ü olacak şekilde yerleştirilmiş olmasının temin edilmesi hayati önem taşımaktadır.',
            'El merdivenleri alana girmek ya da alandan çıkmak amacıyla kullanılmalı ve platform olarak kullanılmamalıdır.',
            'Düşmelere karşı kullanılan donanımları tam ve eksiksiz olarak bilin ve uygun zamanda uygun ekipmanı kullanın. Düşmeyi önleyici ekipman (gerekli tüm aksesuarlarıyla birlikte). Kinetik enerjiyi absorbe eden frenleme ekipmanı (gerekli tüm aksesuarlarıyla birlikte). Vücudu boşlukta tutabilen donanım (paraşütçü kemeri)',
            'Koruyucu baretlerinizi yüksekte çalışırken mutlaka giyin.Yaptığınız işe göre uygun sağlamlıkta ve rahat kullanımı olan baretleri tercih edin.İnşaat işleri, özellikle iskeleler ve yerden yüksek çalışma platformların üstünde, altında veya yakınında yapılan işler, kalıp yapımı ve sökümü, montaj ve kurma işleri, iskelede çalışma ve yıkım işleri vs…',
            'Kaymayı önleyici ve delinmeye dayanıklı ayakkabılarınızı çatı vb. çalışma alanlarında mutlaka giyin. Çatı işleri vb.',
            'Emniyet kemerlerinizi yüksekte yaptığınız çalışmalarda mutlaka giyin.Emniyet kemerinizin yaptığınız çalışmaya uygun olup olmadığını mutlaka formeninize veya İş Güvenliği Mühendisinize danışarak teyit edin.- İskelelerde çalışma- Prefabrik parçaların montajı- Direk ya da sütunlarda çalışma ,vb..',
            'Emniyet kemerlerinin yeterli olmadığı durumlarda ek güvenlik halatlarına ihtiyaç vardır.Bu durumları mutlak öğrenin ve gerektiğinde kullanın.',
        ],
        'bolumler' => NULL,
        'taahhut' => 'Her işçi kendi emniyetini almakla yükümlüdür. Yapılacak işin gereğine uygun olarak iş güvenliği ile ilgili her türlü gereç ve vasıtaları ilgililerden isteyip kullanmak zorundadırlar. Aksi takdirde meydana gelebilecek kaza ve neticelerden ve iş güvenliği talimatlarını bilmemekten dolayı geçireceğiniz veya sebep olacağınız bir kazadan dolayı sorumlu olacağınızı unutmayınız. Yukarıdaki maddeleri tamamen okudum.
İş güvenliği ile ilgili eğitimi aldım, işim ve ilgili hususlarda tatbiki gerekenlerin tatbikini yapacağım, eğer yetkim dışında ise derhal yetkilisine ve işyerine müracaat edeceğim. Bu talimat tutanağını tamamen okuyup anlayarak ve iş güvenliği kaidelerine ve talimatlarına harfiyen riayet edeceğimi bildirerek imza ediyorum.',
    ],
    [
        'baslik' => 'ÇATI KAPLAMA İŞLERİNDE GÜVENLİ ÇALIŞMA TALİMATI',
        'kategori' => 'insaat_saha',
        'dokuman_no' => 'İn_ÇTKP_tlmt',
        'aciklama' => 'İnşaat talimatı — 20 madde',
        'kkdler' => [],
        'maddeler' => [
            'Hergün çalışmaya başlamadan önce çalışılacak alanla ilgili risk faktörleri hakkında taşeron teknik personeli ve iş güvenliği sorumlusu tarafından bilgi alınmalıdır. İş güvenliği gözetiminde güvenlik tedbirleri alındıktan sonra çalışma yapılmalıdır.',
            'Tüm çalışanlar şantiye içinde gereken kişisel koruyucu malzemeleri ( baret, yelek, ayakkabı ) kullanmalıdır.',
            'Çalışma öncesi tüm kaldırma donanımları ve bağlantı ekipmanlarının kontrolü yapılmalı, yetkisiz kişiler dışında kaldırma ekipmanları kesinlikle kullanılmamalıdır.',
            'Kaymayı önleyici ve delinmeye dayanıklı ayakkabılar çatı vb. çalışma alanlarında mutlaka giyilmelidir.',
            'İşçilerin emniyet kemerinin kancalarını takacakları yerler, çalışılan yere uygun bir şekilde gerçekleştirilmelidir. Çatının veya binanın yatay kirişlerinde yapılan çalışmalarda, belli sağlam dikmeler arasına yatay can halatlar gerilmelidir. İşçiler emniyet kemerlerinin kancalarını bu halatlara geçirerek ve hat boyunca emniyetli olarak yürüyebilmelidir.',
            'Çatıda yapılan çalışmalar için öncelikle, çatıya çıkış ve çatıdan iniş sırasında düşme riski olan yerlerde uygun önlemler alınmalıdır. Çalışılan pozisyonlara uygun olarak, erişim noktaları düzenlenmelidir.',
            'Düşmeye karşı önlemler, çalışma başlamadan önce planlanmalı, uygulanmalı ve çalışma bitene kadar sürdürülmelidir.',
            'Çatıda çalışacak kişiler yeterli bilgiye, deneyime ve yeteneğe sahip olmalıdır.',
            'Çatı çalışmalarının sürdürüldüğü kısmın altındaki ve çevresindeki tehlikeli alana girilmemelidir.',
            'Düşen malzemelerden oluşabilecek yaralanmaları önlemek için gerekli tedbirler (ağ, vs.) alınmalıdır. Eğer mümkünse büyük ve ağır malzemeler çatıya taşınmaktan kaçınılmalıdır.',
            'Malzemelerin düşebilecek yerlerde birikmesine izin verilmemelidir.',
            'Malzemelerin indirilmesi için kapalı çöp bacası veya yük asansörü kullanılmalıdır.',
            'Düşen malzemeler ölümlere yol açabilirler. Bu nedenle çatıdan aşağıya hiçbir malzeme atılmamalıdır.',
            'İşçilerin çatı üzerinde veya kenarında veya kırılgan malzemeden yapılmış herhangi bir yüzey üzerinde çalışmak zorunda olduğu hallerde; kırılgan maddeden yapılmış yüzeyde dalgınlıkla yürümelerini veya yere düşmelerini önleyecek önlemler alınmalıdır.',
            'Çatı üzerindeki yoğun çalışma sırasında, yuvarlanan veya kayan işçilerin düşmesini engellemek için korkuluk ve etek tahtaları çakılmalıdır.Bu korkuluklar dengesini yitiren bir işçinin düşmesine engel olacak sağlamlıkta olmalıdır.',
            'Çatı eğimlerinin 45 dereceyi aştığı durumlarda, çatı,kaymayı önleyici çatı el merdiven ya da iskele platformu gibi bir destek sistemi olmaksızın çalısmaya uygun değildir. Gerekli tedbirler almadan kesinlikle çatı üzerine çıkılmamalıdır.',
            '40-50 km/saat’in üzerindeki rüzgar hızlarında, zeminin kaygan ve buzlu olması halinde, yüksekte yapılan her türlü montaj, bakım ve onarım çalışmaları durdurulmalıdır.',
            'Yüksek kodlarda bulunan çalışma yerlerinde, bir yerden bir yere giderken, emniyetli olmayan kestirme yollardan geçilmemeli, şaka yapılmamalı ve gayri ciddi çalışılmamalıdır.',
            'Vinç ile alınan malzemeler çatı mahya seviyesinin 50 cm üzerine talimatla kaldırılmalıdır, tali kirişlere dik olacak şekilde, taşıyıcı kirişler üzerine yavaşça ve dikkatlice indirilmelidir.',
            'Malzeme ağırlığının taşıyıcı kiriş taşıma kapasitesinden daha az olmamasına bilhassa dikkat edilmelidir ve en az 2 yerden çatı kontrüksiyona bağlayarak korumaya, sabitlemeye alınmalıdır.',
        ],
        'bolumler' => NULL,
        'taahhut' => 'Her işçi kendi emniyetini almakla yükümlüdür. Yapılacak işin gereğine uygun olarak iş güvenliği ile ilgili her türlü gereç ve vasıtaları ilgililerden isteyip kullanmak zorundadırlar. Aksi takdirde meydana gelebilecek kaza ve neticelerden ve iş güvenliği talimatlarını bilmemekten dolayı geçireceğiniz veya sebep olacağınız bir kazadan dolayı sorumlu olacağınızı unutmayınız. Yukarıdaki maddeleri tamamen okudum.
İş güvenliği ile ilgili eğitimi aldım, işim ve ilgili hususlarda tatbiki gerekenlerin tatbikini yapacağım, eğer yetkim dışında ise derhal yetkilisine ve işyerine müracaat edeceğim. Bu talimat tutanağını tamamen okuyup anlayarak ve iş güvenliği kaidelerine ve talimatlarına harfiyen riayet edeceğimi bildirerek imza ediyorum.',
    ],
    [
        'baslik' => 'SIVA İŞLERİNDE GÜVENLİ ÇALIŞMA TALİMATI',
        'kategori' => 'insaat_saha',
        'dokuman_no' => 'İn_SIVA_tlmt',
        'aciklama' => 'İnşaat talimatı — 33 madde',
        'kkdler' => [],
        'maddeler' => [
            'Sıva, boya, badana ve kaplama işlerinde kullanılacak malzemeler şantiyede daha önceden belirlenen uygun düz zeminlerde ve güvenli bir şekilde depolanacak, malzeme güvenlik bilgi formlarındaki (MSDS), kullanım, depolama ve boş kapların imhasına ilişkin bilgiler dikkate alınacaktır.',
            'Bina içerisinde malzemelerin taşınacağı güzergâhlar temizlenecek ve döşeme üzerinde herhangi bir engel bulunmayacaktır.',
            'Sıva ve badana uygulamaları makine yardımı ile yapılıyorsa (hazır sıva makinesi, alçı püskürtme makinesi, harç karıştırma mikseri vb.) işe başlanmadan önce çalışanlara makineler hakkında eğitim verilecek, makinelerde bu konuda tecrübeli ustaların çalışmaları sağlanacak, makinalarda elektrik kaçağı olup olmadığı kontrol edilecektir.',
            'Makinelerin periyodik bakımları düzenli olarak yaptırılacak, bakımlarla ilgili raporlar şantiyede dosyalanacaktır.',
            'Çalışma sırasında makinelerde olabilecek aksaklıklarda, işçilerin makineye rastgele müdahale etmesi engellenecek ve durum derhal yetkili kişiye bildirilecektir.',
            'Kapalı ortamlarda boya işlerinde çalışanların çalışma saatleri ayarlanacak, uzun süre havasız ortamda çalışmalarına izin verilmeyecek ve çalışma ortamının havalandırılması sağlanacak, daha uzun çalışmalarda uygun hava maskeleri verilecektir.',
            'Dış cephelerin sıva, badana, boya ve kaplaması sırasında iskelede çalışan ekibe iskelede güvenli çalışabilmeleri için gerekli İSG bilgileri verilecektir.',
            'Seviye farkı olan yerlerde yapılan çalışmalarda çalışan işçilerin paraşüt tipi emniyet kemeri kullanmaları zorunludur.',
            'Sıva, boya, badana ve kaplama imalatlarında çalışan işçilerin tamamının baret kullanması zorunludur.',
            'Sıva, boya, badana ve kaplama imalatları sırasında sıpa iskeleler yerine, uygun ebatta, üzerinde en az 80 cm genişliğinde çalışma alanı bulunan, tekerlekli, en az 2 tekerleğinde fren sistemi bulunan, 90 cm yüksekliğinde sağlam (125 kg. yüke dayanabilecek) korkuluğa sahip ve basamaklı çalışma platformları kullanılacaktır.',
            'Dış cephe çalışmaları sırasında, aşağıda çalışanların veya geçenlerin üzerine malzeme düşmesine karşı, çalışma alanının altında gerekli önlemler (perde, paravan vb.) alınacaktır.',
            'İşyerine iyi uyumuş ve dinlenmiş olarak zinde bir şekilde gelinecektir.',
            'Uyuşukluğa neden olan bir ilaç kullanmaya başlamış iseniz, durumu amirlerinize bildirin.',
            'Çalışırken yüzük, zincir, kolye vs. gibi takıları kullanmayın.',
            'Sarkıntılı, bol veya düğmelenmemiş elbiseleri giymeyin, boyun bağı takmayın.',
            'Baretinizi çene bağını iptal etmeden, başınıza sıkıca oturacak şekilde ayarladıktan sonra şantiye sahası içerisinde takın.',
            'Çalışırken sigara içmeyin.',
            'Yaptığınız işe uygun iş eldiveni, iş ayakkabısı ve koruyucu gözlük ile çalışın.',
            'Boya veya inceltici kimyasallar hakkında bilgi edinin, kullanımda malzeme güvenlik bilgi formlarında (MSDS) yer alan bilgileri esas alarak hareket edin.',
            'Çalışma ortamında yeterli aydınlatmayı sağlayın, aydınlatma ve ısınmada açık ateş kullanmayın.',
            'Ekip halinde çalışırken iskele üzerinde belli bir yerde toplanmayın.',
            'İskele yakınında elektrik nakil hatları varsa önlem alınmasını isteyin.',
            'Seviye farkı olan her yüksekliklerde, kayma ve düşme tehlikesi bulunan korkuluksuz yerlerdeki çalışmalarda, asansör ve dış cephe boşluklarında yapılan çalışmalarda kolonları tüm gövdeyi saran paraşüt tipi emniyet kemeri kullanın. Kırılacak zeminler üzerinde önlem (çatı merdiveni vb.) almadan yürümeyin.',
            'Emniyet kemeri kancasının takılacağı yer bulunamazsa, iki aks arasına düşey ve yatay yaşam halatı çekin ve kemerin kancasını bu halata takarak çalışın. Gerektiğinde düşey halata mobil düşüş tutucu aparat takın.',
            'Yukarıdan malzeme düşme ihtimali olan durumlarda ve üstte başka ekip çalışması sürdüğünde, gerekli önlemleri almadan ve ekiplerin doğru iş planlaması yapılmadan işe başlamayın.',
            'Emniyet kemerinin kullanılamadığı yerlerde düşme ve kayma tehlikesi varsa çalıştığınız yerin alt tarafına naylon iplerden örülmüş güvenlik ağları gerdirin.',
            'Yağışlı ve rüzgarlı havalarda gerekli önlemler alınmadan kaygan platform üzerinde çalışmayın, gerekiyorsa çalışmayı bırakın.',
            'Size verilen kişisel koruyucu malzemeleri mutlaka kullanın.',
            'Çalıştığınız yerde asılı bulunan iş güvenliğiyle ilgili ikaz ve uyarı levhalarına mutlaka uyun.',
            'Batıcı ve kesici takımları çalışırken cebinizde taşımayın.',
            'Kullanacağınız seyyar el merdivenlerinin kaymaz, sağlam, temiz olmasına dikkat edin. Merdivenin kurulmasında kurma yön ve şeklinin emniyetli olmasına özen gösterin, merdivenin duvardan açıklığının merdiven boyunun en fazla ¼’ü olmasına dikkat edin, boşluk taraflarında seyyar merdivenleri kullanmak yasak olup buralarda sehpa tipi korkuluklu iskeleler kullanılmalıdır.',
            'Karşılaştığınız aksaklık, tehlike ve uyuşmazlıkları derhal ekip başına veya amirlere bildirin.',
            'İş arkadaşlarınızla daima uyumlu çalışın ve yardımlaşın.',
        ],
        'bolumler' => NULL,
        'taahhut' => 'Her işçi kendi emniyetini almakla yükümlüdür. Yapılacak işin gereğine uygun olarak iş güvenliği ile ilgili her türlü gereç ve vasıtaları ilgililerden isteyip kullanmak zorundadırlar. Aksi takdirde meydana gelebilecek kaza ve neticelerden ve iş güvenliği talimatlarını bilmemekten dolayı geçireceğiniz veya sebep olacağınız bir kazadan dolayı sorumlu olacağınızı unutmayınız. Yukarıdaki maddeleri tamamen okudum.
İş güvenliği ile ilgili eğitimi aldım, işim ve ilgili hususlarda tatbiki gerekenlerin tatbikini yapacağım, eğer yetkim dışında ise derhal yetkilisine ve işyerine müracaat edeceğim. Bu talimat tutanağını tamamen okuyup anlayarak ve iş güvenliği kaidelerine ve talimatlarına harfiyen riayet edeceğimi bildirerek imza ediyorum.',
    ],
    [
        'baslik' => 'BOYA İŞLERİNDE GÜVENLİ ÇALIŞMA TALİMATI',
        'kategori' => 'insaat_saha',
        'dokuman_no' => 'İn_boya_tlmt',
        'aciklama' => 'İnşaat talimatı — 24 madde',
        'kkdler' => [],
        'maddeler' => [
            'İş Güvenliği ile ilgili verilen; baret, çelik burunlu ayakkabı/bot/çizme, baş ve yüz maskesi, koruyucu gözlük, emniyet kemeri, eldiven gibi koruyucu malzemeleri işin gereğine göre mutlaka kullanılmalıdır.',
            '2 m den yüksekte çalışmalarda mutlaka emniyet kemerleri kullanılmalıdır.',
            'Boya ve solventlerin parlayıcı/patlayıcı/zehirleyici olduğu unutulmamalıdır.',
            'Boya ve solventlerin yüz, göz ve deri ile teması önlenmelidir. Bulaşma anında orayı bol suyla yıkayıp doktora/sağlık memuruna görünülmelidir.',
            'Kapalı alanlarda solvent buharının tabana çöktüğü unutulmamalı. Gerekirse tabanı süpürülmelidir.',
            'Boyayı püskürtme istikametinde insan ve eşya bulunmamasına dikkat edilmelidir.',
            'Boya yapılan alanlarda birşey yenmemelidir, zehirlenebilirsiniz.',
            'Boya işlemi esnasında, kapalı alanların devamlı havalandırılması sağlanmalıdır.',
            'Boya yapılan yerlerde sigara içilmemeli, ateş yakılmamalı, kıvılcım çıkartan el aletleri (spiral taş gibi) kullanılmamalıdır.',
            'Elektrik kontağı ve arkı yangına sebebiyet vereceğinden; elektrik düğmesi, priz gibi elektrik tesisatı civarında solvent buharı oluşmamasına dikkat edilmelidir.',
            'Boya ve solvent depolanan mahallin/odanın içinde priz ve elektrik düğmesi bulundurmamalı. Bu mekânın dışına alınmalıdır.',
            'Boru tünelleri, tanklar gibi kapalı ve dar yerlerde çalışma yaparken diğer personel ile birbirinizi görebilecek şekilde uygulama yapılmalı ve bu alanların devamlı havalandırılması sağlanmalıdır.',
            'Gerekli ikaz levhaları icabeden yerlere asılmalı ve bunlara riayet edilmelidir.',
            'Asitten zarar görebilecek seyyar kabloları, kullanılan ipleri gözden geçirip tehlike arz edenler devreden çıkartılmalıdır.',
            'Çift komponentli boyaları azar azar karıştırınız ve ortam ısısının yükselmemesine dikkat edilmelidir.',
            'Boşalan boya ve solvent tenekelerini çalışma mahallinde bulundurmamalıdır.',
            'Boya mahallinde ihtiyaç fazlası dolu boya ve solvent tenekeleri bulundurmamalı/depolanmamalıdır.',
            'Açık havada tabanca ile boya yaparken rüzgâr daima arkanıza alınmalı ve boyanın mümkün olduğunca etrafa dağılmamasına dikkat edilmelidir.',
            'Süresi dolan boya maskesinin filtresi değiştirilmelidir. Aksi takdirde hiçbir fayda sağlamaz.',
            'Seyyar demir/alüminyum merdivenle çalışırken elektrik tellerine 3 m. fazla yaklaşılmamalıdır.',
            'Boya işinde kullanılan tüm malzemeler iş bitiminde iyice temizlenmelidir.',
            'Temizlik işinde kullanılan ve üzerine boya, solvent bulaşmış bulunan üstüpü, bez gibi malzemeler çok kolay tutuşabileceğinden boya yapılan ortamdan uzaklaştırılmalı, ayrı bir yerde üstü kapalı özel çöp bidonlarına atılmalı veya güvenli bir yerde yakarak imha edilmelidir. Bunlar diğer çöplerle karıştırılmamalıdır.',
            'Tertipli çalışılmalı. Çalışma alanında yeteri kadar yangın söndürme cihazı bulundurulmalı ve kullanımını öğrenilmeli. Üzeriniz basınçlı hava ile temizlenmemelidir.',
            'Söndürme cihazı dışında yangın anında kullanılmak üzere, ayrıca su dolu büyük bir kap içinde paçavra, eski battaniye veya bez bulundurulmalıdır. Her işçi kendi emniyetini almakla yükümlüdür.',
        ],
        'bolumler' => NULL,
        'taahhut' => 'Yapılacak işin gereğine uygun olarak iş güvenliği ile ilgili her türlü gereç ve vasıtaları ilgililerden isteyip kullanmak zorundadırlar. Aksi takdirde meydana gelebilecek kaza ve neticelerden ve iş güvenliği talimatlarını bilmemekten dolayı geçireceğiniz veya sebep olacağınız bir kazadan dolayı sorumlu olacağınızı unutmayınız. Yukarıdaki maddeleri tamamen okudum.
İş güvenliği ile ilgili eğitimi aldım, işim ve ilgili hususlarda tatbiki gerekenlerin tatbikini yapacağım, eğer yetkim dışında ise derhal yetkilisine ve işyerine müracaat edeceğim. Bu talimat tutanağını tamamen okuyup anlayarak ve iş güvenliği kaidelerine ve talimatlarına harfiyen riayet edeceğimi bildirerek imza ediyorum.',
    ],
];
