{{-- Kaynak: kullanıcının verdiği Mehse_com_Hizmet_Sozlesmesi_ve_KVKK.docx — metin BİREBİR,
     değiştirmeyin; yeni sürüm gelince bu dosyayı yeniden üretip config isg.kayit.yasal_metinler.kvkk.revizyon'u güncelleyin.
     [..] alanları belgede doldurulmamış yer tutuculardır (sarı işaretli). --}}
<p>Başvuru sahipleri ve hesap kullanıcıları  |  İnternet sitesi: Mehse.com</p>
<p>Revizyon: 30.09.2026  |  Sürüm: 1.2</p>
<p>Bu metin, Mehse platformundaki başvuru, deneme, abonelik, hesap yönetimi, destek ve faturalama süreçlerinde kişisel verilerin işlenmesi hakkında bilgi verir. Köşeli parantezli alanlar, yayımdan önce fiilî süreçlere göre doldurulmalıdır.</p>
<h3>1 Veri sorumlusu</h3>
<p>Mehse <mark class="mehse-yasal-bos">[tam ticaret unvanı veya işletme sahibi gerçek kişinin adı]</mark>, bu metinde açıklanan kendi başvuru ve hesap yönetimi işlemleri bakımından veri sorumlusudur.</p>
<p>Adres: <mark class="mehse-yasal-bos">[açık posta adresi]</mark>. Başvuru e-postası: <mark class="mehse-yasal-bos">[e-posta]</mark>. KEP, varsa: <mark class="mehse-yasal-bos">[KEP]</mark>. Vergi / MERSİS bilgisi, varsa: <mark class="mehse-yasal-bos">[bilgi]</mark>. Mehse firma adı; Mehse.com platformun internet sitesi adresidir.</p>
<h3>2 İşlenen kişisel veriler ve toplama yöntemi</h3>
<p>Başvuru ve kullanımın niteliğine göre gerekli ölçüde şu veriler işlenir: kimlik bilgileri (ad, soyad); iletişim bilgileri (e-posta, telefon, adres); mesleki ve kurumsal bilgiler (işyeri veya OSGB unvanı, temsil yetkisi, sorumlu müdür bilgisi ve gerektiğinde mesleki belge / yetki numarası); fatura ve ödeme kayıtları; işlem güvenliği bilgileri (IP adresi, oturum, erişim ve işlem kayıtları); başvuru notları ve destek yazışmaları. Tüzel kişiye ait bilgiler, gerçek kişiyle ilişkilendirildiği ölçüde kişisel veri kapsamındadır.</p>
<p>Veriler; Mehse.com başvuru formları, kullanıcı paneli, destek ve e-posta kanalları, sözleşme ve fatura belgeleri ile teknik kayıtlar üzerinden elektronik ortamda; varsa imzalı evrak üzerinden fiziki ortamda toplanır. İşleme otomatik yollarla veya veri kayıt sisteminin parçası olmak kaydıyla otomatik olmayan yollarla yapılır.</p>
<p>Müşterilerin platforma yüklediği çalışan, işyeri ve profesyonel verileri için veri sorumlusu ve veri işleyen rolleri somut sürece göre belirlenir. Mehse, müşteri adına veri işlediği işlemlerde hukuka uygun ve belgelenmiş talimatlarla hareket eder; kendi güvenlik yükümlülükleri devam eder. Bu metin, müşteri işyerlerinin çalışanlarına yapılacak ayrı aydınlatmanın yerine geçmez.</p>
<h3>3 İşleme amaçları ve hukuki sebepler</h3>
<p>Kimlik, iletişim ve başvuru bilgileri; bireysel başvurunun değerlendirilmesi, deneme / aboneliğin kurulması, hesap açılması ve hizmetin yürütülmesi için sözleşmenin kurulması veya ifasıyla doğrudan ilgili ve gerekli olması şartına dayanılarak işlenir (Kanun m.5/2-c).</p>
<p>Kurumsal kullanıcı ve temsilci bilgileri; temsil yetkisinin kontrolü, yetkilendirme ve kurumsal hizmet iletişimi için temel hak ve özgürlüklere zarar vermemek kaydıyla veri sorumlusunun meşru menfaati kapsamında işlenir (m.5/2-f). İlgili kişinin bizzat sözleşme tarafı olduğu işlemlerde m.5/2-c uygulanır.</p>
<p>Faturalama için gerekli kimlik, adres, vergi ve işlem kayıtları; kanuni mali yükümlülüklerin yerine getirilmesi amacıyla hukuki yükümlülük şartına dayanılarak işlenir (m.5/2-ç).</p>
<p>IP, oturum ve erişim kayıtları; hesap güvenliği, dolandırıcılığın ve yetkisiz erişimin önlenmesi için temel haklara zarar vermemek kaydıyla meşru menfaat şartına dayanılarak işlenir (m.5/2-f).</p>
<p>Destek kayıtları; sözleşmenin tarafı olan kullanıcının hizmet talebini karşılamak için m.5/2-c, kurumsal kullanıcıya destek sunmak için m.5/2-f kapsamında işlenir. Uyuşmazlıkla ilgili kayıtlar, bir hakkın tesisi, kullanılması veya korunması için gerekli olması şartıyla işlenir (m.5/2-e).</p>
<p>Bu şartlara dayanmayan, açık rıza gerektiren ayrı bir faaliyet varsa faaliyete özgü bilgilendirme yapılır ve rıza ayrıca alınır. Sağlık verileri gibi özel nitelikli veriler bu metinle verilmiş genel bir izne dayanılarak işlenmez.</p>
<h4 class="mehse-yasal-bolum">Aktarım Saklama ve Haklar</h4>
<h3>4 Kişisel verilerin aktarılması</h3>
<p>Hizmetin yürütülmesi için gerekli veriler; barındırma ve teknik destek hizmeti sağlayıcılarına hizmetin işletilmesi, e-posta sağlayıcılarına hizmet bildirimlerinin iletilmesi, muhasebe hizmeti sağlayıcılarına mali işlemler, hukuki danışmanlara hakların korunması ve yetkili kamu kurumlarına kanuni yükümlülüklerin yerine getirilmesi amaçlarıyla, gerekli ölçüde ve hukuki şartlar sağlanarak aktarılabilir. Yurt içi aktarımlar, Kanunun 8 inci maddesindeki şartlara uygun ve amaçla sınırlı yapılır. Fiilen kullanılan alıcı grupları: <mark class="mehse-yasal-bos">[doğrulayınız; kullanılmayanları çıkarınız]</mark>.</p>
<p>Sunucu, yedekleme, e-posta veya uzaktan erişim yoluyla yurt dışına aktarım durumu: <mark class="mehse-yasal-bos">[var / yok; ülke, alıcı grubu, amaç ve hukuki mekanizma]</mark>. Aktarım varsa, Kanunun 9 uncu maddesi uyarınca uygulanabilir yeterlilik kararı, uygun güvence veya şartları oluşmuş arızi aktarım hâli somut olarak belirlenir ve ilgili kişiler somut süreç hakkında bilgilendirilir. Bu metin tek başına yurt dışı aktarım izni oluşturmaz.</p>
<h3>5 Saklama süresi ve imha</h3>
<p>Kişisel veriler, işleme amacı için gerekli süre ve uygulanabilir kanuni saklama yükümlülükleriyle sınırlı tutulur. Süre sonunda silinir, yok edilir veya anonimleştirilir. Devam eden uyuşmazlıklarla ilgili kayıtlar, gerekli ölçüde ve erişimleri sınırlandırılarak tutulabilir.</p>
<p>Yayımlanacak somut süreler veya belirleme ölçütleri:</p>
<ul>
    <li>Sonuçlanmayan başvuru kayıtları: <mark class="mehse-yasal-bos">[süre ve gerekçe]</mark>.</li>
    <li>Hesap ve sözleşme kayıtları: <mark class="mehse-yasal-bos">[süre ve gerekçe]</mark>.</li>
    <li>Fatura ve mali kayıtlar: <mark class="mehse-yasal-bos">[uygulanacak yasal süre]</mark>.</li>
    <li>Erişim ve güvenlik kayıtları: <mark class="mehse-yasal-bos">[süre ve gerekçe]</mark>.</li>
    <li>Destek kayıtları ve yedekler: <mark class="mehse-yasal-bos">[süre ve silme döngüsü]</mark>.</li>
</ul>
<h3>6 Haklarınız ve başvuru yolları</h3>
<p>6698 sayılı Kanunun 11 inci maddesi kapsamında; kişisel verilerinizin işlenip işlenmediğini öğrenme, işlenmişse buna ilişkin bilgi isteme, işleme amacını ve amaca uygun kullanılıp kullanılmadığını öğrenme, yurt içinde veya yurt dışında aktarıldığı üçüncü kişileri bilme, eksik veya yanlış işlenen verilerin düzeltilmesini isteme, kanuni şartlar çerçevesinde silinmesini veya yok edilmesini isteme, düzeltme ve silme işlemlerinin verilerin aktarıldığı üçüncü kişilere bildirilmesini isteme, münhasıran otomatik sistemler aracılığıyla analiz sonucu aleyhinize bir sonuç ortaya çıkmasına itiraz etme ve hukuka aykırı işleme nedeniyle zarara uğramanız hâlinde zararın giderilmesini talep etme haklarına sahipsiniz.</p>
<p>Haklarınıza ilişkin taleplerinizi, kimliğinizi doğrulamaya imkân verecek bilgiler ve talebinizle birlikte <mark class="mehse-yasal-bos">[veri sorumlusunun posta adresi]</mark> adresine yazılı olarak veya Veri Sorumlusuna Başvuru Usul ve Esasları Hakkında Tebliğdeki koşullara uygun diğer yöntemlerle iletebilirsiniz. KEP: <mark class="mehse-yasal-bos">[adres]</mark>. Daha önce bildirdiğiniz ve sistemde kayıtlı e-postanızla başvuru kanalı: <mark class="mehse-yasal-bos">[adres]</mark>. Başvurular, niteliğine göre en kısa sürede ve en geç 30 gün içinde sonuçlandırılır. Başvuru kural olarak ücretsizdir; ayrıca maliyet gerektiren hâllerde Kurulca belirlenen tarifedeki ücret alınabilir.</p>
<p>Başvuruda ad, soyad, yazılı başvuruda imza, vatandaşlığa göre T.C. kimlik numarası veya ilgili yabancı kimlik bilgisi, tebligata esas adres, varsa e-posta / telefon ve talep konusu belirtilir; talebe ilişkin belgeler eklenir. Gereksiz kimlik belgesi veya başka kişilere ait veriler gönderilmemelidir.</p>
<p>Başvurunuz reddedilirse, cevap yetersizse veya 30 gün içinde cevap verilmezse Kişisel Verileri Koruma Kuruluna şikâyet edebilirsiniz. Şikâyet süresi, cevabı öğrendiğiniz tarihten itibaren 30 gün ve her hâlde başvuru tarihinden itibaren 60 gündür. Veri sorumlusuna başvuru yolu tüketilmeden Kurula şikâyet edilemez.</p>
<h3>7 Bilgilendirme beyanının anlamı</h3>
<p>Başvuru ekranında kullanılacak ifade: “Mehse KVKK Aydınlatma Metnini okudum ve kişisel verilerimin işlenmesi hakkında bilgilendirildim.”</p>
<p>Bu beyan yalnızca aydınlatma metninin sunulduğunu ve bilgilendirmeyi ifade eder; kişisel verilerin her amaçla işlenmesine, yurt dışına aktarılmasına veya pazarlama iletilerine açık rıza oluşturmaz. Aydınlatma, kişisel veriler elde edilirken yapılır ve bir onay kutusunun işaretlenmesine bağlı tutulmaz. Açık rıza gerektiren faaliyetlerde ayrı, belirli bir amaca ilişkin ve özgür iradeye dayalı tercih alınır. Hizmet sözleşmesinin kabulü ayrı alanda gösterilir.</p>
