{{-- Kaynak: kullanıcının verdiği Mehse_com_Hizmet_Sozlesmesi_ve_KVKK.docx — metin BİREBİR,
     değiştirmeyin; yeni sürüm gelince bu dosyayı yeniden üretip config isg.kayit.yasal_metinler.sozlesme.revizyon'u güncelleyin.
     [..] alanları belgede doldurulmamış yer tutuculardır (sarı işaretli). --}}
<p>İnternet sitesi: Mehse.com  |  Revizyon: 30.09.2026  |  Sürüm: 1.1</p>
<p>Bu sözleşme, Mehse tarafından sunulan İSG yönetim platformunun kullanımını düzenler. Köşeli parantezli bilgiler, hizmet sunulmadan önce tamamlanacaktır.</p>
<h3>1 Taraflar</h3>
<p>Sağlayıcı: Mehse adıyla faaliyet gösteren <mark class="mehse-yasal-bos">[gerçek kişi adı veya tam ticaret unvanı]</mark>. Adres: <mark class="mehse-yasal-bos">[adres]</mark>. Vergi dairesi ve numarası: <mark class="mehse-yasal-bos">[bilgi]</mark>. MERSİS numarası, varsa: <mark class="mehse-yasal-bos">[bilgi]</mark>. Bildirim e-postası ve KEP, varsa: <mark class="mehse-yasal-bos">[bilgi]</mark>.</p>
<p>Müşteri: <mark class="mehse-yasal-bos">[OSGB / işyeri / bireysel uzman adı veya unvanı]</mark>. Adres: <mark class="mehse-yasal-bos">[adres]</mark>. Vergi dairesi ve numarası: <mark class="mehse-yasal-bos">[bilgi]</mark>. Yetkili kişi: <mark class="mehse-yasal-bos">[ad soyad]</mark>. Bildirim e-postası: <mark class="mehse-yasal-bos">[bilgi]</mark>.</p>
<p>Mehse firma adı, Mehse.com ise internet sitesi adresi olarak kullanılır; sözleşmenin tarafı yukarıda kimliği belirtilen Sağlayıcıdır.</p>
<h3>2 Konu ve kapsam</h3>
<p>Platform; işyeri ve çalışan kayıtları, görev ve saha ziyaretleri, risk değerlendirmesi, eğitim, acil durum, belge ve süre takibi gibi İSG süreçlerinin dijital ortamda yönetimine yardımcı olur. Kullanıma açılan modüller satın alınan pakette belirtilir. Yazılım kullanımı, ayrıca sözleşme yapılmadıkça iş güvenliği uzmanlığı, işyeri hekimliği, OSGB hizmeti, resmî onay veya hukuki danışmanlık hizmeti oluşturmaz. Hatırlatmalar ve örnek belgeler, müşterinin mevzuata uygunluk kontrolünün ve yetkili kişilerin incelemesinin yerine geçmez. Platform, işyeri, görevlendirme, saha ziyareti ve performans gibi operasyonel kayıtların tutulmasına imkân sağlar. Resmî kurumlarla entegrasyon veya resmî bildirim hizmeti, yalnızca pakette açıkça belirtilmişse kapsama dahildir.</p>
<h3>3 Başvuru deneme ve abonelik</h3>
<p>Müşteri, başvuru bilgilerinin doğru ve güncel olduğunu ve temsil ettiği kurum adına işlem yapmaya yetkili bulunduğunu beyan eder. Başvurunun Sağlayıcı tarafından kabulü ve sözleşmenin müşteri tarafından onaylanması üzerine kullanıcı hesabı açılır. Deneme süresi ve başlangıç tarihi başvuru ekranında gösterilir; deneme süresi en fazla 90 gündür. Deneme tanımlanmamışsa ücretli paket, müşterinin ayrıca kabul ettiği koşullarla başlatılır.</p>
<p>Paket ve modüller: <mark class="mehse-yasal-bos">[doldurunuz]</mark>. Kullanıcı / işyeri / depolama sınırı: <mark class="mehse-yasal-bos">[doldurunuz]</mark>. Deneme süresi: <mark class="mehse-yasal-bos">[yok veya gün sayısı]</mark>. Abonelik başlangıcı ve bitişi: <mark class="mehse-yasal-bos">[tarihler]</mark>. Hizmet bedeli ve para birimi: <mark class="mehse-yasal-bos">[bilgi]</mark>. KDV durumu: <mark class="mehse-yasal-bos">[dahil / hariç]</mark>. Ödeme dönemi ve vadesi: <mark class="mehse-yasal-bos">[bilgi]</mark>. Destek kanalı ve saatleri: <mark class="mehse-yasal-bos">[bilgi]</mark>.</p>
<p>Deneme sonunda ücretli aboneliğe geçiş müşterinin ayrıca onayına bağlıdır. Yenileme ve yeni dönem fiyatı önceden bildirilir; müşterinin açık kabulü olmadan yeni dönem için ücret doğurulmaz. Paket dışı hizmetler ayrıca fiyatlandırılır ve onay alınmadan uygulanmaz.</p>
<p>Kullanım yalnızca müşterinin kendi faaliyetleri ve yetkili olduğu işyerleriyle sınırlıdır. Bireysel uzman, işyeri ve OSGB hesaplarında erişim, tanımlanan rol ve paket yetkilerine göre sağlanır.</p>
<h3>4 Müşterinin yükümlülükleri</h3>
<p>Müşteri; hesapları yetkili kişilerle sınırlar, erişim bilgilerini korur, ayrılan kişilerin yetkisini kaldırır ve şüpheli erişimi gecikmeden bildirir. Girilen verilerin doğruluğunu, yükleme ve işleme yetkisini, belgelerin güncelliğini ve yasal işlemlerin zamanında tamamlanmasını sağlar. Platforma zararlı yazılım yükleyemez, yetkisiz erişim deneyemez ve başkalarının haklarını ihlal edemez. Kanunen izin verilen hâller saklı kalmak üzere yazılımı kopyalayamaz, yeniden satamaz veya tersine mühendislik yapamaz. Müşteri, 6331 sayılı Kanun ve ilgili mevzuattan kaynaklanan kendi yükümlülüklerini yerine getirir. Çalışan ve diğer üçüncü kişilerin verilerini işlerken gerekli hukuki şartları sağlar ve kendi aydınlatma yükümlülüğünü yerine getirir.</p>
<h3>5 Hizmetin sunulması bakım ve destek</h3>
<p>Sağlayıcı, kararlaştırılan modülleri sunar; erişim yetkileri, gizlilik, bakım ve güvenlik için uygun teknik ve idari tedbirleri uygular. Planlı bakım ve önemli kesintileri mümkün olduğunda önceden bildirir. Kesintisiz veya hatasız çalışma garantisi verilmez; bu hüküm Sağlayıcının sözleşmeden ve kanundan doğan sorumluluğunu kaldırmaz. Yedekleme sıklığı, saklama süresi ve geri yükleme hedefleri: <mark class="mehse-yasal-bos">[fiilî hizmet koşulları yazılacaktır]</mark>. Destek, kabul edilen paket kapsamı ve bildirilen çalışma saatlerinde sunulur. Müşteri kaynaklı internet, cihaz ve erişim sorunları müşterinin kontrol alanındadır. Taraflar hizmet kesintisinin etkisini azaltmak için iş birliği yapar.</p>
<h4 class="mehse-yasal-bolum">Veri Güvenliği ve Sorumluluk</h4>
<h3>6 Kişisel veriler ve gizlilik</h3>
<p>Taraflar, kişisel verileri yalnızca belirli ve hukuka uygun amaçlarla, gerekli ölçüde işler. Sağlayıcı, başvuru, hesap ve faturalama verileri bakımından kendi faaliyetleri ölçüsünde veri sorumlusudur. Müşterinin platforma yüklediği çalışan ve işyeri verilerindeki roller, işleme amaçlarını ve araçlarını belirleyen tarafa göre değerlendirilir. Sağlayıcı, müşteri adına veri işlediği işlemlerde müşterinin belgelenmiş hukuka uygun talimatlarıyla hareket eder.</p>
<p>İşlenen veri türleri, ilgili kişi grupları, alt hizmet sağlayıcılar, erişim yetkileri, ihlal bildirimi, veri iadesi ve imhası, veri işleme ekinde somutlaştırılır. Sağlık verileri gibi özel nitelikli veriler, uygun hukuki şart ve erişim tedbirleri sağlanmadan yüklenmez. Gizli bilgiler hizmetin ifası ve hukuki zorunluluklar dışında açıklanmaz. Bir veri ihlalinin öğrenilmesi hâlinde taraflar gecikmeden birbirini bilgilendirir ve kanuni bildirim süreçlerinde iş birliği yapar. Taraflar, öğrendikleri ticari sırları diğer tarafın izni veya hukuki zorunluluk olmadan açıklamaz. Başvuru ve hesap süreçlerinin ayrıntıları ekli aydınlatma metninde açıklanır. Yurt dışı aktarım varsa ayrıca uygulanabilir hukuki koşullar sağlanır.</p>
<h3>7 Fikrî mülkiyet ve veri sahipliği</h3>
<p>Platformun yazılımına ve tasarımına ilişkin haklar Sağlayıcıya veya ilgili hak sahibine aittir. Müşterinin yüklediği içerikler üzerindeki hakları korunur. Sağlayıcı bu içerikleri hizmeti sunmak için gereken ölçüde kullanabilir; ayrıca hukuki dayanak olmadan reklam, pazarlama veya başka müşterilerin yararına kullanamaz. Müşteriye, abonelik süresince paket sınırları içinde sınırlı, devredilemez ve münhasır olmayan kullanım hakkı tanınır. Yazılımın kullanımı fikrî mülkiyet haklarının devri anlamına gelmez.</p>
<p>Müşteri, sona ermeden itibaren 30 gün içinde kayıtlarının mevcut dışa aktarım formatlarında teslimini isteyebilir. Format ve teslim yöntemi: <mark class="mehse-yasal-bos">[bilgi]</mark>. Yasal saklama yükümlülüğü bulunmayan kayıtlar bu sürenin ardından belirlenen imha takvimine göre silinir veya anonimleştirilir. Yedeklerden silinme süresi: <mark class="mehse-yasal-bos">[bilgi]</mark>. Saklanması zorunlu verilerin erişimi amaçla sınırlandırılır. Fesih, müşterinin kendi yasal kayıt saklama yükümlülüğünü ortadan kaldırmaz.</p>
<h3>8 Sorumluluğun kapsamı ve sınırı</h3>
<p>Platform bir yönetim ve takip aracıdır. Mevzuata uyum, resmî bildirim, risk değerlendirmesi, eğitim ve sağlık gözetimi gibi yükümlülüklerde müşterinin ve ilgili görevlilerin kanuni sorumlulukları devam eder. Hatırlatmanın ulaşmaması veya örnek belgenin kullanılması, bu yükümlülükleri ortadan kaldırmaz.</p>
<p>Sağlayıcı; müşterinin hatalı veri girişi, yetkisiz işlemleri veya kendi yükümlülüklerini yerine getirmemesi nedeniyle doğan sonuçlardan, kendisine yüklenebilen kusur bulunmadıkça sorumlu tutulamaz. Sağlayıcının kendi kusuru ve kanunen üstlendiği güvenlik, gizlilik ve hizmet yükümlülükleri saklıdır.</p>
<p>Kanunen sınırlandırılmasına izin verilen ve ayrıca müzakere edilerek kabul edilen hafif kusura dayalı sözleşmesel zararlar bakımından, Sağlayıcının toplam tazminat sorumluluğu zarara yol açan olaydan önceki 12 ayda bu hizmet için müşterinin ödediği toplam bedelle sınırlıdır. Bu kayıt ayrıca kabul edilmemişse genel sorumluluk hükümleri uygulanır. Bedelsiz denemede sıfır tutarlı bir sorumluluk sınırı uygulanmaz. Kasıt, ağır kusur, kişisel veri ve gizlilik ihlalleri ile kanunen sınırlandırılamayan sorumluluklar bu sınırın dışındadır. Bu sözleşme, kamu kurumlarının ve üçüncü kişilerin kanuni haklarını sınırlandırmaz.</p>
<h3>9 Askıya alma ve fesih</h3>
<p>Ödeme veya diğer sözleşme ihlallerinde, acil güvenlik ve hukuka aykırılık hâlleri dışında, müşteriye yazılı bildirimle 15 gün düzeltme süresi verilir. İhlalin giderilmemesi hâlinde ilgili hizmet askıya alınabilir veya sözleşme feshedilebilir. Acil tedbirler gerekçesiyle müşteriye bildirilir ve risk ortadan kalktığında gözden geçirilir. Esaslı ihlal nedeniyle haklı fesih hakkı her iki taraf için saklıdır. Sağlayıcının kusurundan kaynaklanan sona ermede, sunulmayan döneme ait peşin bedel iade edilir; diğer iadeler emredici hükümler ve kabul edilen paket koşullarına göre belirlenir. Taraflar, kabul edilen paket koşullarındaki ihbar süresine uyarak aboneliği yazılı bildirimle sona erdirebilir. Olağan fesih ihbar süresi: <mark class="mehse-yasal-bos">[gün]</mark>. Fesih; doğmuş alacakları, gizlilik yükümlülüklerini ve hukuken devam etmesi gereken hükümleri ortadan kaldırmaz. Veri teslimi ve silme işlemlerinde 7 nci madde uygulanır.</p>
<h4 class="mehse-yasal-bolum">Yürürlük ve Tarafların Onayı</h4>
<h3>10 Uygulanacak hukuk ve uyuşmazlık</h3>
<p>Bu sözleşmeye Türkiye Cumhuriyeti hukuku uygulanır. Taraflar uyuşmazlıkları öncelikle iyi niyetli görüşmelerle çözmeye çalışır; bu süreç kanuni başvuru sürelerini durdurmaz. Çözüm sağlanamazsa kanunen görevli ve yetkili mahkeme ve icra dairelerine başvurulur. Zorunlu arabuluculuk ve diğer zorunlu başvuru yolları saklıdır. Tarafların hukuki statüsü ve kanuni koşullar doğrulanmadan belirli bir şehir mahkemesi için münhasır yetki öngörülmez.</p>
<h3>11 Yürürlük bildirimler ve değişiklikler</h3>
<p>Müşteri, başvuru ekranında “Mehse Hizmet ve Kullanım Sözleşmesini okudum ve kabul ediyorum” seçeneğini işaretleyerek veya sözleşmeyi imzalayarak kabulünü bildirir. Sözleşme, müşterinin kabulü ve Sağlayıcının başvuruyu onaylamasıyla yürürlüğe girer. Elektronik onayda kabul edilen metnin sürümü, tarih ve onay kaydı saklanır; müşterinin metne erişmesi sağlanır.</p>
<p>Sağlayıcı, güncellemeleri platform veya kayıtlı e-posta üzerinden bildirir. Ücret, kapsam, sorumluluk ve fesih koşullarındaki esaslı değişiklikler müşterinin açık kabulüyle uygulanır; sessiz kalma tek başına kabul sayılmaz. Geçmiş işlemlere geriye dönük koşul değişikliği uygulanmaz. Kanunen zorunlu değişikliklerin uygulanması saklıdır.</p>
<p>Taraflar iletişim bilgilerini güncel tutar. Kanunen özel şekle bağlı bildirimler uygun yöntemle yapılır. Bu sözleşmeye eklenen paket ve hizmet koşulları, taraflarca kabul edildiği ölçüde sözleşmenin parçasıdır. KVKK aydınlatma metni bilgilendirme amacı taşır ve açık rıza yerine geçmez.</p>
<h3>Paket ve eklerin teyidi</h3>
<p>Paket / sipariş numarası: <mark class="mehse-yasal-bos">[bilgi]</mark></p>
<p>Kabul edilen ücret ve ödeme planı: <mark class="mehse-yasal-bos">[bilgi]</mark></p>
<p>Hizmet başlangıç ve bitiş tarihi: <mark class="mehse-yasal-bos">[bilgi]</mark></p>
<p>Fesih ihbar süresi: <mark class="mehse-yasal-bos">[gün]</mark></p>
<p>Destek ve yedekleme koşulları: <mark class="mehse-yasal-bos">[ek adı / sürümü]</mark></p>
<p>Veri işleme eki: <mark class="mehse-yasal-bos">[ek adı / sürümü]</mark></p>
<p>8 inci maddedeki müzakere edilen sorumluluk sınırı: <mark class="mehse-yasal-bos">[kabul edildi / kabul edilmedi]</mark></p>
<p>Ayrı kabul tarihi ve yetkili imzası: <mark class="mehse-yasal-bos">[bilgi]</mark></p>
<p>Hizmet ve Kullanım Sözleşmesini ve yukarıda belirtilen doldurulmuş paket koşullarını okudum ve kabul ediyorum.</p>
<p>Sağlayıcı: Mehse</p>
<p>Yetkili adı ve soyadı: __________________________</p>
<p>Tarih ve imza: _________________________________</p>
<p>Müşteri unvanı veya adı: _______________________</p>
<p>Yetkili adı ve soyadı: __________________________</p>
<p>Tarih ve imza: _________________________________</p>
